### ISSUE TITLE
TODO: Fix the bounds for length-prefixed parameters in protocol messages

### ISSUE THREAD

**Issue by ekr** [ietf-wg-ppm/draft-ietf-ppm-dap#110]
.(E.g., `<23..479>` instead of `<1..2^16-1>`.)]

**Comment by cjpatton** [comment]
@branlwyd and @tgeoghegan raised objections to this change. @branlwyd [suggests](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/578#pullrequestreview-2312881470) we use `1` as the minimum whereever the length prefixed field is never going to be empty and to use `0` otherwise. @tgeoghegan [suggests](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/578#issuecomment-2366835583) we use `0` everywhere.

If I were the tie breaker, I'd vote for just using `0` everywhere. However I think we need to try to get more feedback on this question before we make a call.

**Comment by branlwyd** [comment]
FWIW, I have no objection to using `0` everywhere if that's the popular sentiment. My only objection is to computing to-the-byte minimums for required messages -- it's very easy to get it wrong, and IMO we should handle parsing errors for embedded encoded messages at the point they are parsed, rather than while parsing the message containing them.

**Comment by cjpatton** [comment]
Cross-referencing @bifurcation's feedback on this: https://github.com/cfrg/draft-irtf-cfrg-vdaf/pull/428#pullrequestreview-2323156518
