### ISSUE TITLE
Cost implications of single leader model

### ISSUE THREAD

**Issue by hostirosti** [ietf-wg-ppm/draft-ietf-ppm-dap#130]
Assuming `Aggregators` and `Servers` are running on distinct cloud providers / hosting environments there is an additional egress cost incurred using the `Leader` model where one `Aggregator` coordinates input validation and data collection from all clients and then forwards data shares  / batches to respective `Aggregators` that are part of the setup.

 As of 2021-08-18 there are the following network costs of major cloud providers. *No claim of 100% accuracy*

TL;DR Assuming `Aggregators` / `Servers` running on distinct providers using the Leader model we can assume $50 - $230 / TB added cost for egress network traffic.

//TODO add how many input shares per TB approx.

# Network Cost Comparison across providers

## Ingress Network Cost
*>>cost incurred by clients sending data to `Aggregator(s)`<<*
*all prices per GB*

AWS | Azure | GCP 
----|-------|------
 free | free | free 

## Egress Network Cost
*>>cost incurred by sending data out leaving the provider (e.g. server communication, leader aggregator sending data to other aggregators<<*
*all prices per GB*

AWS | Azure | GCP
-----|-------|------
$0.05-$0.154<sup>1</sup> |   $0.0875 - $0.181<sup>2</sup> |  $0.045 - $0.23<sup>3</sup>

<sup>1</sup> Tiered discount 1GB free, 1GB-10TB, 10TB-50TB, 50TB-150TB, 150TB+ 
<sup>2</sup> Tiered discount 5GB free, 5GB-10TB, 10TB-50TB, 50TB-150TB, 150TB-500TB, 500TB+
<sup>3</sup> Tiered discount 0-1TB, 1-10TB, 10+TB Premium Tier starts at $0.08, Standard Tier goes down to $0.045 Tiered 0-10TB, 10-150TB, 150-500TB

## Intra-Provider Network Cost
*>>cost incurred by sending data within a provider between different regions<<*

### Intra-Continental
*all prices per GB*
Region | AWS | Azure | GCP
---- | ---- | ---- | ----
NA | $0.01-$0.02  |  $0.02 | $0.01
Europe | $0.02 |  $0.02 | $0.02
Asia | $0.09 | $0.08 | $0.05
Oceania | $0.098 | $0.08 | $0.08
MEAA | $0.1105-$0.147 | $0.08 | $0.08
South America | $0.138 | $0.16 | $0.08

### Inter-Continental
*all prices per GB*
Region | AWS | Azure | GCP
---- | ---- | ---- | ----
NA -> * | $0.01-$0.02 |  $0.05 | $0.08-$0.15<sup>1</sup>
Europe -> * | $0.02 |  $0.05 | $0.08-$0.15<sup>1</sup>
Asia, Oceania, Africa -> * | $0.086-$0.098 | $0.08 | $0.08-$0.15<sup>1</sup>
South America -> * | $0.138 | $0.16 | $0.08-$0.15<sup>1</sup>

<sup>1</sup> from/to Indonesia or Oceania2 $0.15 for GCP

**Comment by tgeoghegan** [comment]
Per today's design call, we agreed that we will stick with the leader model in the protocol for now. However, I am going to take a look at what the data egress costs are in Prio v2 relative to the amount of data we are moving, to provide some context on how much $$$ we are really talking about here. Further, I'm going to sketch out what a protocol variant that allows direct client to helper upload would look like, and how much cloud egress such a model would save, so that we have a better idea of how much money is saved.

**Comment by eriktaubeneck** [comment]
I would argue (in line with what I think is the current consensus) that having `Helpers` be minimal and stateless is preferable, however these egress costs will be significant. I propose we consider allowing the `Leader` run a `LeaderProxy` within each cloud provider, which could be specified by within the client, and could result in minimal egress costs. Here is a diagram (as best I could in ascii...), with the assumption that the `LeaderProxy` and `Helper` are within the same cloud, but top and bottom pairs are in different clouds:
```
                     +-------------+    +------------+
            +-------->             |    |            |
+--------+  |  +-----> LeaderProxy <---->   Helper   |
|        |  |  |  +-->             |    |            |
| Client +--|--+  |  +------^------+    +------------+
|        |  |  |  |         |
+--------+  |  |  |         |
            |  |  |         |
+--------+  |  |  |  +------v------+                    +-----------+
|        |  |  |  |  |             |                    |           |
| Client +--+  |  |  |    Leader   <--------------------> Collector |
|        |  |  |  |  |             |                    |           |
+--------+  |  |  |  +------^------+                    +-----------+
            |  |  |         |
+--------+  |  |  |         |
|        |  |  |  |         |
| Client +--|--|--+  +------v------+    +------------+
|        |  |  |  +-->             |    |            |
+--------+  |  +-----> LeaderProxy <---->   Helper   |
            +-------->             |    |            |
                     +-------------+    +------------+
```

One added benefit of such an approach is the all of the egress cost is born by the leader, which further minimizes the responsibility and cost variance on the helpers.

**Comment by cjpatton** [comment]
I've been working on an implementation of PPM instantiated with `prio3`. In order to make this discussion more concrete, I took some measurements of the communication cost for various data types.

The table below contains results for 1000 reports. The first column is the data type (see https://docs.rs/prio/latest/prio/vdaf/prio3); the second column is the total amount of data uploaded by clients to the leader; the third column is the amount of data sent from the leader to the helper; and the final column is the amount of data data sent from the helper to the leader. Data rates exclude HTTP request framing.

| data type | bytes processed | bytes sent | bytes received | 
| ---------- | -----------| ------------- | ------------ |
| Prio3Count64 | 423.8 KB | 276.5 KB | 82.1 KB |
| Prio3Histogram64 (10 buckets) | 837.9 KB | 280.4 KB | 86.0 KB |
| Prio3Sum64 (32 bits) | 2.2 MB | 280.4 KB | 86.0 KB |

Extrapolating, aggregating 1 million reports results in at most 273.8MB of egress, or about $0.06 at $0.23/GB.

The main thing to note here is that the amount of data uploaded by clients depends on the data type, but the amount of data sent from the leader to helper does not. This is because in `prio3` the helper's input share is always constant size, but the leader's depends on the data type. For `hits` on the other hand, the size of each input share is going to be linear in the length of the inputs. This is likely makes the concrete cost much higher, but we should measure it.

**Comment by cjpatton** [comment]
@eriktaubeneck wrote: 
> I propose we consider allowing the `Leader` run a `LeaderProxy` within each cloud provider, which could be specified by within the client, and could result in minimal egress costs. Here is a diagram (as best I could in ascii...), with the assumption that the `LeaderProxy` and `Helper` are within the same cloud, but top and bottom pairs are in different clouds: ...

I'm not sure I see how this architecture helps with the state coordination problem. It seems like LeaderProxy just makes explicit a functionality that the Helper is going to have to implement it anyway. Why does making it explicit help?

**Comment by eriktaubeneck** [comment]
> I'm not sure I see how this architecture helps with the state coordination problem. 
Agreed, I don't believe it has an effect on state coordination. I'm only suggesting this in terms of minimizing cost.

Suppose we have Agg1, Agg2, and Leader, which are in Cloud1, Cloud2, and Cloud3. If a message from Agg1 -> Agg2 needs to actually route through the Leader, i.e. Agg1 -> Leader -> Agg2, then that message would pay egress fees to both Cloud1 and Cloud2.

If instead we had a Leader Proxy running in Cloud1, the message could go from Agg1 -> Leader Proxy (Cloud 1) -> Agg2, which would only pay egress fees to Cloud1. It also has a nice site effect of consolidating all the egress fees onto the Leader.

**Comment by cjpatton** [comment]
Right now we don't have a situation where Agg1 would send a message to Agg2. In fact, for the moment, we don't support more than one helper. In my opinion, addressing this is situation is a bit premature.

**Comment by eriktaubeneck** [comment]
Got it. I misunderstood the added cost concern in this issue. Agreed that this is a premature optimization under current constraints.

**Comment by cjpatton** [comment]
It seems like the ship has sailed on sending report shares directly to the Helper. However there are some other things we might do to minimize bandwidth:

1. Avoid transmitting aggregation job in each job: https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/405
1. Avoid re-transmitting report shares across collection jobs: https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/409
