### ISSUE TITLE
Recovering after batch mismatch

### ISSUE THREAD

**Issue by ekr** [ietf-wg-ppm/draft-ietf-ppm-dap#141]
Note from today's call: the CFRG documents need to specify that after the aggregate phase, the helper and leader need to agree to which shares are valid. Depending on the crypto, this may require the leader to tell the helper which ones were valid, if the helper doesn't get the proof result.

**Comment by cjpatton** [comment]
Options discussed so far:
1. Have the helper wait for an ACK from the leader before aggregating its output share
2. If the helper fails to respond to the request for some reason, have the leader "rewind" the helpers state, either by replaying the previous helper state (may impact anti-replay) or with a special "compensation request", which has the helper deduct the last output share form the total (Robert's idea).
3. Run the protocol with multiple sets of helpers so that, if a fault occurs in one run, another run can be used.

**Comment by cjpatton** [comment]
As of DAP-01, there is a checksum in the AggregateShareReq that's used to confirm that the Aggregators agree on the set of aggregated reports. This is sufficient for "error detection", but we might want to do something for "error correction". I'm going to re-purpose this issue and put it in the parking lot.

**Comment by cjpatton** [comment]
At IETF 118 we decided to close this without doing anything. We already have error detection, and batch mismatch should be exceptionally rare. It's also not clear right now how to do error correction.
