### ISSUE TITLE
Authentication of Collector's query

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#155]
During execution of the collect protocol, the leader is responsible for relaying some parameters of the collect request to the helper, represented by the opaque `output_param` in `CollectReq` and `OutputShareReq` messages introduced by #154. That parameter will always be null/empty/absent for Priov3, but in Hits, it would contain the string prefixes that the collector wants a count of in the result set (and who knows what else in yet-undefined VDAFs).

It's currently possible for the leader (or any actor that can tamper with messages on the network) to insert arbitrary `output_param` into `OutputShareReq` messages. @cjpatton reckons [this is a threat to soundness](https://github.com/abetterinternet/ppm-specification/pull/154#discussion_r718917818). We should think about whether this enables the leader to undermine soundness in any ways beyond the capabilities the threat model already grants it, and if so, introduce collector->helper authentication+integrity. ~Confidentiality~Privacy may not be needed on here because the `output_param` should be identical for helper and leader.

**Comment by tgeoghegan** [comment]
Note that we already protect helper->collector messages with HPKE. Since both sides already advertise HPKE configs, one solve here would be to use that to tunnel a mutually authenticated channel through the leader.

**Comment by cjpatton** [comment]
This is misrepresenting the problem in a few ways. I think the key points are:
1. For soundness we assume both aggregators are honest. Regardless, a network attacker can currently impersonate the leader to the helper because the leader is not authenticated and violate soundness. This is outside of the model for VDAF, but is one of our security considerations for the PPM protocol. This needs to be addressed.
2. For privacy (note that this is not the same thing as confidentiality) we assume just one of the aggregators is honest. The dishonest aggregator may act arbitrarily, including forging the output parameter or the helper's encrypted input share itself. Authentication of the channel can't help us here.

As far as the mechanism for leader authentication: auth-mode for HPKE is a promising direction. One thing we need to think through is whether KCI attacks matter for our setting, since HPKE auth-mode is vulnerable to these: https://www.ietf.org/archive/id/draft-irtf-cfrg-hpke-12.html#sec-properties

**Comment by cjpatton** [comment]
Another option for leader authentication is client certificates for TLS.

**Comment by tgeoghegan** [comment]
What's discussed here is the risk of the leader presenting forged collect request/aggregate share request parameters to the leader. We have a similar problem in the other direction, which is that when satisfying a request to a collect job URI, a leader could throw away the aggregate share computed by the helper, fabricate two totally synthetic aggregate shares that combine into the leader's chosen aggregate result, and then present those to the collector, which has no way of verifying that either share came from the helper.

While discussing this on the ppm@ietf.org mailing list, @cjpatton (citing ekr) observed that we can mitigate that risk by having collectors fetch each aggregate shares directly from each aggregator, enabling it to use TLS to verify each server's identity. This is a good way to solve this attack without adding new cryptography to DAP (e.g., an in-band signature over aggregate shares), though it might introduce new difficulties with ensuring the two aggregators produce aggregate shares over the same set of reports.

**Comment by cjpatton** [comment]
When we ask ourselves what games the Leader can play by exploiting the lack of an authenticated channel between Collector and Helper, there are two buckets of concerns:
1. Privacy: Is there attack that leads to disclosing information about measurements that the attacker can't learn otherwise?
2. Robustness: Is there an attack that leads the Collector to compute the wrong aggregate result?

I don't think we have a privacy issue here. There is definitely a way to attack robustness, assuming the Leader is actively attacking the protocol. However, there are other ways, like tweaking its own aggregate share.

I don't see an obvious way of defeating our goals of privacy or robustness, at least in the threat model for VDAFs where for robustness we assume both Aggregators run the protocol correctly. That said, having the Collector communicate with both Aggregators directly seems like a reasonable defense-in-dpeth measure. If anyone wants this feature, please send a PR.

**Comment by cjpatton** [comment]
For reference, here is the discussion that @tgeoghegan refers to above: https://mailarchive.ietf.org/arch/msg/ppm/3G_WM7L49L1wz0LK9snx7KCSQng/

**Comment by tgeoghegan** [comment]
I feel comfortable not addressing this in the protocol since nobody has articulated a privacy attack, and since we discuss this in the security considerations.

**Comment by chris-wood** [comment]
Agreed. Closing.
