### ISSUE TITLE
addressing collusion

### ISSUE THREAD

**Issue by npdoty** [ietf-wg-ppm/draft-ietf-ppm-dap#173]
The privacy guarantees that motivate this protocol work require non-collusion: if servers collude, all the individual data can be retrieved. As was raised by a few folks at the BOF, methods for addressing collusion or providing users some confidence about non-collusion will be important for evaluating the utility for privacy of this work.

We might want to adjust the charter to not exclude discovery/selection, as that might benefit from hooks to help users choose servers operated by different parties. Or, we might include in the scope some group discussion or recommendation of ways to provide user confidence in non-collusion, even if that won't be defined in the protocol. Or, if there's an implied dependency on some other project to establish co-operative but non-colluding servers, we should make that explicit. Finally, it might be useful to describe a threat model and the implications of colluding servers, to make it easier to evaluate these proposals against alternatives that rely on trusting a server to minimize collected data.

**Comment by tgeoghegan** [comment]
> We might want to adjust the charter to not exclude discovery/selection, as that might benefit from hooks to help users choose servers operated by different parties. 

I think it might be interesting for the PPM WG to eventually consider this, but I don't think it should be in scope for the PPM RFC. My worry is that there's a huge number of ways for a client to agree on PPM task parameters with an aggregator and then authenticate for subsequent API interactions, and trying to describe them would dilute the focus of the PPM RFC. Discovery, especially, is a thorny problem, and I think we'd quickly end up reinventing the X.500 directory. To be clear, it'd be really nice to have something like the X.500 directory out there, but even if it's possible or a good idea to build that, I think it's outside of the scope of the PPM WG and protocol.

> Or, we might include in the scope some group discussion or recommendation of ways to provide user confidence in non-collusion, even if that won't be defined in the protocol. Or, if there's an implied dependency on some other project to establish co-operative but non-colluding servers, we should make that explicit.

I think it's important to remember that the point of PPM isn't to increase a user's confidence that any individual server will comply with the protocol. The point is to reduce the probability of compromise by increasing the number of participants who must defect and collude for privacy to be compromised. So in fact PPM concedes that it's not practical to get guarantees about the behavior of a remote server.

Let's suppose there did exist some scheme that lets a client have confidence in the behavior of a remote server. Then I wouldn't need an algorithm like Prio at all: I would simply apply the scheme to a conventional telemetry system and have it prove to users that it never leaks information (I should credit this observation to Mariana Raykova, who explained it to me when I suggested specifying just the kind of mechanism you're suggesting).

Further, attestation schemes usually rely on some kind of trusted computing base (TCB) outside of the system being measured, like a TPM, ARM TrustZone or Intel SGX. Besides the degree to which these complicate the trust model (e.g., if TrustZone is used, I now have to trust ARM, the SoC manufacturer and the OEM that fused a software signing key into the SoC -- and we haven't thought about multi-tenant virtualization yet), I don't think we want to impose such hardware requirements on PPM implementations.

Finally, I'm not convinced that there are yet any standards for attestation mature enough to be used in a protocol like PPM. What schemes exist today are usually intended to allow a vendor's backend to trust devices manufactured by a vendor, which is a very different proposition than allowing end users to trust an arbitrary remote server. I am aware that there's an [IETF working group](https://datatracker.ietf.org/wg/rats/about/) working in this space. Once that standard becomes mature, I think it'd be worth mentioning, but it's use in PPM implementations would be orthogonal to the PPM protocol itself: attestation tokens or bindings, just like any other kind of authentication, could be included in the HTTP requests in the PPM protocol, or provided to the helper in the [upload extensions](https://github.com/abetterinternet/ppm-specification/blob/main/draft-gpew-priv-ppm.md#upload-extensions-upload-extensions).

> Finally, it might be useful to describe a threat model and the implications of colluding servers, to make it easier to evaluate these proposals against alternatives that rely on trusting a server to minimize collected data.

We do have a [threat model](https://github.com/abetterinternet/ppm-specification/blob/main/draft-gpew-priv-ppm.md#threat-model) section in the document which includes a section discussing [aggregator collusion](https://github.com/abetterinternet/ppm-specification/blob/main/draft-gpew-priv-ppm.md#aggregator-collusion), though all it says is that if all servers collude, the system provides no privacy at all. We could mention that adding more aggregators helps to mitigate these threats (because more aggregators means more servers have to collude), but the protocol is currently only designed to support exactly two aggregators.

**Comment by npdoty** [comment]
> I think it's important to remember that the point of PPM isn't to increase a user's confidence that any individual server will comply with the protocol. The point is to reduce the probability of compromise by increasing the number of participants who must defect and collude for privacy to be compromised. So in fact PPM concedes that it's not practical to get guarantees about the behavior of a remote server.
> 
> Let's suppose there did exist some scheme that lets a client have confidence in the behavior of a remote server. Then I wouldn't need an algorithm like Prio at all: I would simply apply the scheme to a conventional telemetry system and have it prove to users that it never leaks information (I should credit this observation to Mariana Raykova, who explained it to me when I suggested specifying just the kind of mechanism you're suggesting).
> 
> Further, attestation schemes usually rely on some kind of trusted computing base (TCB) outside of the system being measured, like a TPM, ARM TrustZone or Intel SGX. Besides the degree to which these complicate the trust model (e.g., if TrustZone is used, I now have to trust ARM, the SoC manufacturer and the OEM that fused a software signing key into the SoC -- and we haven't thought about multi-tenant virtualization yet), I don't think we want to impose such hardware requirements on PPM implementations.

My understanding is that the privacy advantage of PPM schemes is that it provides privacy without attestation of server behavior *by* splitting up the computation to servers that are known to be operated by different parties. So I'm not suggesting that we include in scope or rely on some perfect attestation of server behavior (I agree, it would make the PPM protocol unnecessary) but that we do consider mechanisms for choosing servers operated by different parties.

If there's no reason at all for a user to believe that the PPM system is operated by multiple non-colluding parties, then I don't see how it's different for the user than relying on the trustworthiness of a single telemetry server.

**Comment by ekr** [comment]
I am strongly opposed to any work to define server selection or discovery at this time. All of the applications I am aware of that people actually intend to deploy involve software vendors selecting (or filtering) the servers, so this doesn't seem helpful.

The reason that it's different for the user is that they can *see* which servers the client is using and make their own decision about whether that's good enough. As a general matter, this is the kind of assurance users have about the behavior of any software they run.

**Comment by tgeoghegan** [comment]
> If there's no reason at all for a user to believe that the PPM system is operated by multiple non-colluding parties, then I don't see how it's different for the user than relying on the trustworthiness of a single telemetry server.

Oooh, that's an interesting point and I see now how it is distinct from a server attesting to the measurements of its code. We do require clients to connect to aggregators over HTTPS, which means they get a server identity in the form of the TLS certificate. At the risk of being glib, I'd say that if the web PKI hasn't figured out a better solution than OV and EV certs to prove to clients that `foo.com` and `bar.com` aren't the same real-world entity, then I don't know if we can do better.

**Comment by cjpatton** [comment]
I agree with Tim and EKR that working on server selection is premature at this time.

**Comment by npdoty** [comment]
Implementer pre-selection or filtering of servers, transparency and authentication of servers, and audits based on that transparency -- these are indeed ways to address the threat of collusion.

If there's agreement among potential implementers that selection/discovery won't be used (at least for now), then it's fine to exclude that from WG scope. But I would suggest that we should discuss the ways collusion will be addressed, in case it has impacts on the protocol design.

**Comment by chris-wood** [comment]
Collusion is now described in the updated security considerations. Technical means to address collusion are definitely out of scope here, as they are for protocols whose properties depend on similar non-collusion assumptions (OHTTP, MASQUE, Privacy Pass, etc). I think we can close this out.
