### ISSUE TITLE
Interaction of anti-replay and flexibility

### ISSUE THREAD

**Issue by ekr** [ietf-wg-ppm/draft-ietf-ppm-dap#183]
Reading through the latest changes on anti-replay it seems like we are foregoing a bunch of flexibility that we may want.

Here's a simple example:
Suppose that I have a measurement that i want to slice by geographic regions. At the moment this is impossible because the anti-replay mechanism requires only one set of aggregations for a given time window. As @cjpatton pointed out to me privately, you can have a different task for each region, but:

1. This is going to be a pain if you want to change your slicing policy later
2. It mostly precludes crosstabs and drilldown 

At minimum, I think we want an anti-replay design to guarantee that any given input share is aggregated at most once but that allows overlapping windows. Eventually, I expect we're going to want to allow multiple aggregation but in restricted ways (otherwise drilldown and crosstabs are hard).

**Comment by chris-wood** [comment]
I agree that flexibility is generally useful, but we need to be careful to not allow any sort of overlapping windows to violate report privacy. We need a better way to reason about what's permissible and what's not here.

**Comment by cjpatton** [comment]
I agree that the ability to filter aggregates by some attribute (region, user agent, etc.) is a useful feature, and I agree that protocol changes will likely be needed to support it. I'm not sure what this has to do with anti-replay, however:

> At minimum, I think we want an anti-replay design to guarantee that any given input share is aggregated at most once but that allows overlapping windows. Eventually, I expect we're going to want to allow multiple aggregation but in restricted ways (otherwise drilldown and crosstabs are hard).

A collect request may specify any batch interval the collector wants, so long as the conditions in {{batch-parameter-validation}}. This allows one to "drill down" on clients with certain attributes while still maintaining some privacy invariants.

But to emphasize @chris-wood's point, these conditions may not be sufficient. A more careful analysis is needed (especially for applications that use DP).

**Comment by ekr** [comment]
>  I'm not sure what this has to do with anti-replay, however:

The following text forbids overlapping batches, which are necessary for both drilldown and crosstabs

> In addition, for any report whose nonce contains a timestamp that falls in a batch interval for which it has completed at least one aggregate-share request (see Section 4.3.2), the helper MUST send an error messsage in response rather than its next VDAF message. Note that this means leaders cannot interleave a sequence of aggregate and aggregate-share requests for a single batch.

**Comment by cjpatton** [comment]
Ah, indeed it does. In fact, this seems like it prevents any report from being aggregated more than once (even as required for protocols like Poplar). This needs to be fixed regardless.

**Comment by cjpatton** [comment]
So I think this is the condition we want. It needs to be enforced by both the leader and helper (though at different times), so I'll try to speak in terms of a generic aggregator.

Before it processes a report share, the aggregator first checks if the report pertains to a batch that has already been collected.  This is the case if the aggregator is the leader and has completed a collect request for a batch containing the report, or if the aggregator is a helper and has completed an aggregate-share request for a batch containing the report (see {{aggregate-share-request}}). It also checks if the report has been "observed". This is the case if the report was used in a previous aggregate request.
                               
* If the report has not yet been observed but is contained by a batch that has   been collected, then the aggregator returns an error rather than process the report share further. This prevents additional reports from being aggregated after its batch has already been collected.              
                               
* If the report has been observed but has not been collected, then it returns an error rather than continue processing. This  prevents a report from being used more than once in a batch.

In particular, we *only* process a report if either it has been observed *and* has been collected *or* it has never been observed and is not contained by a batch that has been collected.

I believe this allows overlapping batches to be collected without interfering with anti-replay.

**Comment by cjpatton** [comment]
Superseded by #489.
