### ISSUE TITLE
reconsider reliance on strict ordering

### ISSUE THREAD

**Issue by bdaehlie** [ietf-wg-ppm/draft-ietf-ppm-dap#190]
The PPM specification relies on strictly enforced ordering in a couple of places:

Example 1: "aggregator_endpoints: A list of URLs relative to which an aggregator's API endpoints can be found. Each endpoint's list MUST be in the same order. The leader's endpoint MUST be the first in the list."

Example 2: "encrypted_input_shares contains the encrypted input shares of each of the aggregators. The order in which the encrypted input shares appear MUST match the order of the task's aggregator_endpoints (i.e., the first share should be the leader's, the second share should be for the first helper, and so on)."

This technically solves the intended problem just fine as far as I can tell but it's a scheme that's prone to implementation mistakes, and if a mistake is made it'll be harder to spot than it probably needs to be. I would consider some kind of explicit tagging of resources rather than relying on consistent ordering in lists.

**Comment by tgeoghegan** [comment]
This is addressed by the changes in https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/393: because we now have exactly two aggregators, we can change structures like report to have explicit `leader_share` and `helper_share` fields instead of a vector of shares and these awkward semantics around ordering. We'll close this once #393 lands.

**Comment by cjpatton** [comment]
Closed by #393.
