### ISSUE TITLE
Collect requirements

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-ppm/draft-ietf-ppm-dap#195]
Let's start with an overview of the problem as I understand it. Currently, batch management is dealt with by dividing the time into a contiguous list of batch windows, each of size min_batch_duration epochs. This is illustrated below (T denotes the T’th batch window):

~~~
|...| T - 1 |  T  | T + 1 |...|
~~~

Each report indicates an epoch that places it uniquely into one batch window. 

When Collectors request the aggregate shares for a batch window, they indicate the interval of time they are interested in collecting aggregate results. This request is constrained in that the interval must be a multiple of the batch window size (min_batch_duration), though it can exceed more than one batch window. For example, a Collector can request aggregate shares for a single batch window T (marked with asterisks), as follows:

~~~
|...| T - 1 |  T  | T + 1 |...|
            *******
~~~

A Collector can also request aggregate shares for multiple, consecutive batch windows T and T+1 as follows:

~~~
|...| T - 1 |  T  | T + 1 |...|
            ***************
~~~

For privacy, each collect request must correspond to some minimum number of measurements, called the min_batch_size. If the aggregators do not have enough report shares to satisfy the request, they must respond with an error. 

Intiuitively, this requirement is meant to esnure that the collect requests cannot be abused to learn individual measurements contributed to an aggregate output. However, the current batch scheme doesn't abide by this requirement. To see why, assume there exists a batch window T in which min_batch_size reports fall. Moreover, assume that there exists only one report in the T+1 window. Assume further the Collector makes the following pair of requests:

1. out1 = Collect(T, T+1)
2. out2 = Collect(T)

This would be a reasonable sequence of requests if, for example, the Collector wanted to drill down to get data for a more fine-grained batch window. However, if both requests were satisfied given the current set of reports, the delta between out1 and out2 would allow the Collector to learn the value of the single individual report in the window T+1. In general, the protocol should prohibit privacy violations of this form.

One way to rule out such privacy violations is to require that each batch window covered by a collect request contain at least min_batch_size reports. (In the example above, the first collect request above would be prohibited because T+1 has just one report.) However, this is perhaps overly restrictive. We want queries to be flexible enough to allow one to slice batches differently, but this needs to be done such that privacy violations cannot occur. 

Given the above, here’s an attempt to formalize the batch query constraint requirement. Let Ci = Collect(Ti,..., Tn), i <= n denote a collect request for the batch interval Ti,...,Tn. For each Ci there exists a unique Si = {r | Ti,...,Tn} where |Si| >= B. That is, Si is the set of reports included in the aggregate covered by the interval Ti,...,Tn, and its size is at least B, where B is min_batch_size.

Based on this, the requirement can simply be stated as follows. Given Ci,...,Cq collect requests, it must not be possible for the collector to reconstruct an aggregate of over a report set S* such that |S*| < B . The Collector can run any number set operations, including intersection, union, and difference, using the output sets Si,...,Sq.

There's a number of questions that might follow from this:

- Is this the right requirement? If not, how should it be tweaked?
- If so, should the protocol specify how to enforce it, or defer that to the implementations? If we assume that collect requests will always agree on their aggregate inputs, then maybe we can simply rely on this and each aggregator's own "collect request validation implementation" to ensure the batch constraints aren't violated. 
- If we do decide to specify its enforcement, how should aggregators check collect requests for correctness while supporting query flexibility? For example, as in #183, what if one wanted to include a "space dimension" with a query, e.g., "give me the aggregate for all reports in time Ti,..,Tj for this given User-Agent" or whatever, then one shouldn't be able to abuse this to violate the requirement above.

There may be other questions that fall out of this as well, but hopefully this gets the ball rolling.

**Comment by tgeoghegan** [comment]
Currently, we have a task parameter `max_batch_lifetime` defined as:
> The maximum number of times a batch of reports may be
>  used in collect requests.

In a task where `max_batch_lifetime` (which I prefer to think of as a privacy budget) is 1, the `(out1, out2)` attack is defeated because after doing `Collect(T, T+1)`, the aggregators will refuse to service `Collect(T)`, since the `max_batch_lifetime` for `T` has been consumed. However I'm not sure if that works for tasks where `max_batch_lifetime > 1`, as will be the case for poplar1 (which successive rounds of prefix queries are made by the collector).

What if we require that once a batch window has been included in a collect request over `Ti...Tn`, it can only appear in later collect requests over supersets of `Ti...Tn`. i.e., after doing `Collect(T, T+1)`, `Collect(T, T+1, T+2)` is permitted, but `Collect(T)` is not. This would make the state tracking quite a bit more complicated for the aggregators, though.

**Comment by divergentdave** [comment]
Tim: Requiring that later collect requests to be either a superset or disjoint to each prior collect request wouldn't be sufficient to meet the requirement, as a privacy-attacking collector could just order their requests differently. If T had `min_batch_size` reports in it, and T+1 had one report, they could issue `Collect(T)`, followed by `Collect(T, T+1)`, and then take the difference to isolate the value of the lone report in T+1. While no aggregator under any rule would allow `Collect(T+1)`, we will have to apply more strict conditions to avoid this difference-of-aggregates attack.

I have an intuitive argument that deciding whether a set of collect requests could produce an aggregate over S* such that |S*| < B could be computationally hard. If the VDAF in use is prio3, we can represent each collect request with a pair of vectors, one vector of the additive aggregates in the result, and one vector ("hot encoded") that signifies which epoch the results came from. Let the report vector have dimension equal to the number of epochs in the time period we're analyzing, (call it N) and each element will be 0 if the corresponding epoch isn't part of the collect request, or equal to the number of reports in the epoch if it is included, |{r | Ti}|. The total number of reports in a collect request is equal to the element-wise sum of this report vector, which is the taxicab metric. We know that for each report vector, this sum is greater than or equal to B, `min_batch_size`. A privacy-attacking collector can take a linear combination of the additive aggregate results from the collect requests, and we can take the same linear combination of the corresponding report vectors to track which reports are included, and with which multiplicity. Now, our requirement begins to look like a lattice problem. We start with a set of the report vectors with taxicab norm >= B, and we want to know whether the lattice they generate has any vectors with taxicab norm < B.

(Caveats: I don't know whether lattice problems are as hard with the taxicab metric as with the typical length norm. If the attacker somehow arrives at the aggregate for 2\*Ti, they could divide by a small multiple to recover it, and the lattice view of the problem would be insufficient. I'm not sure whether there exists a combination of collect requests for which an attacker could reconstruct 2\*Ti but not Ti, or some other small multiple. These report vectors have a fairly restrictive structure, as they each have only one consecutive run of nonzero elements; this may make the lattice problem easier than the general case.)

Moreover, here's a pathological example to consider: Let B=10, and let N=100. Say that T0 has one report, and T1 through T99 each have B reports. Our attacker first issues `Collect(T0, T1)`, `Collect(T1, T2)`, `Collect(T2, T3)`, ... `Collect(T98, T99)`. Each successive request covers either B+1 or 2B reports. While the one-sided set difference of `Collect(T0, T1)` and `Collect(T1, T2)` is only one report, the attacker can't recover a `prio3` aggregate of the lone report in T0, as it's confounded by the influence of T2. This continues through the rest of the collect requests on two epochs. Now, the collector issues a request `Collect(T99)`. If the aggregators do not reject this request, the collector will be able to violate privacy by back-calculating the value of the aggregate of `Collect(T0)`, with only one report, which should not be permitted.

With this pathological example in mind, defining a collect request acceptance rule that only checks over some fixed time horizon could be troublesome. And, since we have to consider differences of collect requests, each additional collect request we include in our analysis could up to double the number of subsets we look at. (no good if the number of collect requests considered can be arbitrarily large) I think we will have to make some trade-off to be less-than-maximally permissive in what sorts of patterns of collect requests we allow, so we can preserve privacy of reports in sparse epochs, while making the on-line decision to allow or reject a collect request simpler.

One simple rule that we could adopt: Every collect request must either not overlap any previous non-aborted collect requests, or have an identical start time and interval to all overlapping non-aborted collect requests. This would allow for what I imagine to be normal operation, continuously collecting over the minimum interval, and then retrying with longer intervals if incoming reports dip below `min_batch_size`. However, it would prohibit any attempts to "temporally drill down" in situations that would otherwise not violate privacy. Are there use cases which would be better served by that than collecting over smaller intervals and summarizing aggregates? Do we contemplate VDAFs which cannot be re-aggregated, like percentile calculations? (`poplar1` counts from separate aggregations could be combined, though they may miss some results that are just under the threshold in each interval, but would have been above in a combined interval)

**Comment by simon-friedberger** [comment]
Would it be a good middle-ground to always split the client space into disjoint sets? That would simplify the computation of what is allowed, as David described above, but would still allow some flexibility to drill-down into results, as long as the disjoint sets don't get too small.

The reasoning is that, given two sets A and B, with A ⊆ B, and ΣB = X, ΣA = Y, clearly the difference B\A  has ΣB\A = X-Y. So, to keep the privacy requirements, B\A must have `min_batch_size` elements as well.

**Comment by tgeoghegan** [comment]
I was thinking about collect requirements for [Prio3Aes128Histogram](https://cfrg.github.io/draft-irtf-cfrg-vdaf/draft-irtf-cfrg-vdaf.html#name-prio3aes128histogram), and I'm now wondering if the definition and enforcement of collect protocol privacy requirements might depend on the VDAF in use, and thus some portion of this will have be defined at the VDAF layer.

Our thinking thus far is that DAP aggregators would have to enforce a minimum number of contributions within a collect request's batch interval. The appeal of this approach is that it can be applied generically regardless of the VDAF in use and depends on a single shared parameter that's easy to apply. But suppose someone deploys Prio3Aes128Histogram, picks a reasonable minimum batch size, but happens to choose their bucket boundaries such that one of the buckets always contains a single contribution. Does that violate the privacy of the individual who reported that value?

A straightforward fix here would be to say that an aggregator should refuse to release a Prio3Aes128Histogram aggregate share unless each bucket has either zero contributions or enough contributions to meet some a privacy threshold. But introducing special cases for VDAFs at the DAP layer seems wrong, so perhaps the enforcement of this kind of thing should be specified in the VDAF's [`out_shares_to_agg_share`](https://cfrg.github.io/draft-irtf-cfrg-vdaf/draft-irtf-cfrg-vdaf.html#name-aggregation-2) function, which would now optionally return an error if privacy requirements aren't met?

**Comment by simon-friedberger** [comment]
I think this has to be handled not just at the VDAF side of things but in the task definition. The impact of the collected information on privacy and the leakage of the specific aggregration function are task specific and need to be be handled there.

I am not sure how straightforward your fix would be, given that aggregators don't see how many entries there are in a bucket. So this would be another validation step. But actually a post-aggregation validation step might be a useful extension. 🤔

**Comment by BranLwyd** [comment]
If we do view this as a privacy violation, it's a rather sticky one: as Simon points out, the collector is the first entity that would be able to determine how many reports any given bucket contains (since it unshards the aggregate shares into an aggregate result). But once the collector has computed the aggregate result it has exposed itself to the privacy-violating measurement, and we must trust that the collector will act unilaterally to do the right thing. In contrast, the other privacy protections such as `min_batch_size` are implemented by both the leader & the helper aggregators (i.e. two separate, non-colluding entities) and are implemented without revealing the privacy-violating measurements.

**Comment by divergentdave** [comment]
Here are two alternate collect interval rules, which would allow aggregators to efficiently validate requests, while both preventing difference-of-aggregates attacks and allowing the collector more flexibility than the "non-overlapping or identical" rule above.

For the first rule, let us add another task parameter that is the duration between "fenceposts". This duration should be a multiple of `min_batch_duration`. (or, it could be defined in terms of a number of `min_batch_duration` windows) Every timestamp that is a multiple of this duration is identified as a "fencepost" instant. Then, the rule is that collect intervals may not cross fenceposts, and all combinations of current and past collect intervals between two fenceposts should not reveal the aggregate over less than `min_batch_size` reports. Aggregators can check this by exhaustively trying all combinations of previously used collect request intervals between the fenceposts, short-circuiting with success if every `min_batch_duration` window between the fenceposts has more than `min_batch_size` reports, or other methods. The main downside of this rule is that it introduces another parameter, and it must be set to carefully balance competing concerns. If the fencepost interval is too small for actual report traffic, such that an entire fencepost interval has fewer than `min_batch_size` reports, then data will be irrevocably lost. If the fencepost interval is too large, relative to `min_batch_duration`, then collectors may inadvertently cause the aggregators to consume too much CPU, if they trigger exhaustive checking on too many intervals. It also limits the time spans that the collector can compute aggregates over, but if we assume parameters are well chosen, it would usually be possible to split a time span of interest at fenceposts, and do aggregation summarization outside of DAP.

For the second rule, we require that batch intervals are always a power-of-two multiple of `min_batch_duration`. We also require that batch intervals start at a timestamp that is a multiple of their duration. Now, the set of permissible batch intervals form an infinite binary tree, where the leaf nodes are all of the minimum sized intervals, and each level up combines two neighboring valid batch intervals. The rule the aggregators enforce is very simple: the batch interval's start time and duration must meet the above multiple and alignment rules, there must be `min_batch_size` reports inside the batch interval, and there must be `min_batch_size` reports inside the batch interval's sibling interval in the binary tree. We can identify this sibling interval's start time by taking the batch start time, dividing by the duration, XORing with 1, and multiplying by the duration again. The upside of this rule is that it makes the job of the aggregators very simple (we only care about the reports and not about previous collect requests, plus we only check report counts in two intervals). I can imagine that collectors could adaptively switch between requesting different collect interval widths as time marches on, so that they can always aggregate across the entire timeline, even if report counts dip. The downside is that it imposes fairly structured limitations on batch intervals.

**Comment by cjpatton** [comment]
We've addressed at least the core privacy issue here. We might be able to squeeze more utility out of DAP with a fancier batch-boundary enforcement algorithm, but perhaps we should wait to work on this until we need to.

**Comment by cjpatton** [comment]
Related to #489.
