### ISSUE TITLE
Aggregation idempotency

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-ppm/draft-ietf-ppm-dap#226]
From @tgeoghegan:

Suppose we have a task with max_batch_lifetime = 1. Consider:

1. Leader makes an AggregateShareReq for some batch interval.
2. Helper services the request, and marks that batch interval as having been collected once.
3. Helper attempts to transmit an AggregateShareResp to leader, but the message is truncated.

Now, if the leader retries its AggregateShareReq, the helper will refuse the request because the batch interval's lifetime has been consumed. So, to allow the leader to retry this request, the helper has to be willing to resend previously computed aggregate shares.

Issue from #223.

**Comment by BranLwyd** [comment]
This issue also affects the aggregation process: if an aggregation step fails in a similar way, the helper might believe it has "stepped" a VDAF preparation to step `N+1` while the leader still believes it is at step `N`.

One strawman solution would be having the helper store the "current" aggregation step & the "previous" aggregation step, then updating the PPM specification to have the leader indicate which "step number" it is on when sending aggregate requests (since VDAF does not & I suppose should not have to carry this information). I think this would make the aggregation steps effectively idempotent.

**Comment by tgeoghegan** [comment]
I believe this got addressed in the DAP-04 HTTP API refactor, except that the `{{collect-aggregate}}` section doesn't explicitly mention that the helper should be willing to service multiple requests to `POST {helper}/tasks/{task-id}/aggregate_shares` for the same `batch_selector`. We'll use this issue to improve the language in DAP-05.
