### ISSUE TITLE
Add metadata definition

### ISSUE THREAD

**Issue by simon-friedberger** [ietf-wg-ppm/draft-ietf-ppm-dap#276]
It would be convenient for testing purposes if we could just collect some random data and also send that data as metadata for comparison.

Since we already discussed that we might need other metadata for slicing I think it would be good to add a definition for it. Could probably be as simple as saying "there are `n` opaque metadata bytes with `n`, it's meaning and usage defined by the task".

**Comment by cjpatton** [comment]
I agree with Chris W., it seems like the `extensions` field of the `Report` could be used for this purpose.

**Comment by tgeoghegan** [comment]
Also, if we're specifically talking about enabling correctness testing (i.e., verifying that the aggregates that come out of the pipeline match the real sums over the original inputs), then we've had luck with deterministically deriving inputs from a timestamp (or in the case of DAP, the report nonce), so that the collector can re-derive the inputs without any additional communication channel between protocol participants.

**Comment by chris-wood** [comment]
@simon-friedberger given the above, are we OK to close this issue, or do you think there are spec changes that need to happen?

**Comment by simon-friedberger** [comment]
Seems good to me!
