### ISSUE TITLE
Polling collect URI changes the Leader's state

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#288]
When the Collector issues a collect request to the Leader, the Leader responds with a URI the Collector can poll later on to get the (encrypted) aggregate result. This is done via an HTTP GET to the collect URI returned by the Leader.

My understanding is that the Leader is free to remove the aggregate results from storage thereafter. (See https://github.com/cloudflare/daphne/issues/53 for discussion.) The spec doesn't require this request to be authenticated, so it's possible for someone to cause the Leader to delete this state before the Collector has a chance to fetch it.

This issue can be solved by:
1. requiring the Leader to store results for some period of time;
2. making the collect URI hard to predict (e.g., by sticking a random number in the URI string); or
2. requiring authentication for this endpoint.

(2.) seems easiest to implement, but may be tricky to spell. Any thoughts on this?

**Comment by tgeoghegan** [comment]
> My understanding is that the Leader is free to remove the aggregate results from storage thereafter.

That's not what [section 4.4.1](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#name-collection-initialization) says:

> The leader MUST retain a collect job's results until the collector sends an HTTP DELETE request to the collect job URI, in which case the leader responds with HTTP status 204 No Content.
>
> [OPEN ISSUE: Allow the leader to drop aggregate shares after some reasonable amount of time has passed, but it's not clear how to specify that. ACME doesn't bother to say anything at all about this when describing how subscribers should fetch certificates: https://datatracker.ietf.org/doc/html/rfc8555#section-7.4.2]

That text is consistent with [@chris-wood's idea](https://github.com/cloudflare/daphne/issues/53#issuecomment-1191499038). So I argue the current situation is (1). We do have to solve the problem of how long a leader can wait before tossing collect results -- or maybe we don't, since ACME doesn't bother to. But we could use this issue to discuss that question.

re: (2): I think we should avoid as much as possible imposing requirements on the construction of URIs and relative paths[^1]. An implementation should feel free to generate unpredictable collect job URIs (Janus randomly generates a v4 UUID) but I don't think DAP should mandate it, just so we don't have to write the text to spell it out.

re: (3): I have a hard time imagining a deployment where the `/collect` endpoint and collect job URIs wouldn't be authenticated[^2], but my position on authn in DAP is that we shouldn't specify anything, allowing implementations to use any authn scheme they want that is composable with HTTP. At most we ought to state requirements (e.g., "the channel between aggregators must be mutually authenticated and confidential") but avoid mandating how those requirements are met (e.g., "the aggregators must use mTLS").

[^1]: The precedent here is ACME, which actually doesn't specify URIs at all. Instead, implementations expose a [directory endpoint](https://datatracker.ietf.org/doc/html/rfc8555#section-7.1.1) which in turn guides clients to the URIs to hit to create orders, or accounts, or whatever. That said, we shouldn't do exactly what ACME does because (1) AFAIK the BCP that mandated this part of ACME's design has been revised and (2) forcing a directory lookup (that is, an extra HTTP round trip) every time an ACME subscriber wants to issue a new cert (roughly once per 90 days) is not so bad, but forcing a directory lookup every time a DAP client wants to upload a measurement seems wasteful.
[^2]: For argument's sake: maybe a deployment wants to make the results of some aggregation public, but in such settings, the collector could combine the aggregate shares into results and then stick them into a CDN instead of making it the leader's problem. Not to mention that the collector is probably most capable of transforming aggregate results into some other format that's better suited for public consumption.

**Comment by chris-wood** [comment]
> re: (3): I have a hard time imagining a deployment where the /collect endpoint and collect job URIs wouldn't be authenticated[2](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/288#user-content-fn-2-cc44bdbddf183583de77b5b1e755da8e), but my position on authn in DAP is that we shouldn't specify anything, allowing implementations to use any authn scheme they want that is composable with HTTP. At most we ought to state requirements (e.g., "the channel between aggregators must be mutually authenticated and confidential") but avoid mandating how those requirements are met (e.g., "the aggregators must use mTLS").

I agree with this. I don't think DAP should specify or even mandate authentication, for the reasons Tim mentioned, but also because the aggregate outputs are encrypted only to the intended collector. Giving those encrypted aggregate shares to an unauthorized party seems fine based on the properties of HPKE.

**Comment by BranLwyd** [comment]
FWIW, the current DAP spec text:

> The leader MUST retain a collect job's results until the collector sends an HTTP DELETE request to the collect job URI

implies (at least to my reading) that the leader must indeed retain the results until an explicit `DELETE` is sent from the collector [1]. I agree that it would be very nice if an aggregator could drop collect results eventually without requiring an explicit request from the collector to do so -- that's consistent with [Chris Wood's idea](https://github.com/cloudflare/daphne/issues/53#issuecomment-1191499038) but inconsistent (IMO) with the current specification text.

If I'm not missing anything, I can prep a small PR fixing this up.


[1] To be very pedantic, following the [HTTP GET semantics](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#GET), the leader could choose to send a representation indicating that the results are gone; but strictly following the text of DAP, the leader would still be required to retain the results. Given that these results would be inaccessible from an outside observer, this is a somewhat academic distinction -- IMO another good reason to make a change here.

**Comment by tgeoghegan** [comment]
@cjpatton we took a change here to improve the text discussing how long leaders should hold on to collect job results, and I think questions about authentication of the collect job URIs is captured by #293. Are there any outstanding concerns about whether polling collect job URIs causes state changes?
