### ISSUE TITLE
Editoral: Use underscores in enum variants instead of dashes

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#314]
We use dashes in enums:

```
  enum {
    batch-collected(0),                                                             
    report-replayed(1),
    report-dropped(2),                                                              
    hpke-unknown-config-id(3),
    hpke-decrypt-error(4),
    vdaf-prep-error(5),
    batch-saturated(6),
  } ReportShareError;
```

I'm not sure how got on this kick (might be my fault!), but I would prefer underscores, mainly for consistency with RFC 8446:

```
  enum {
    batch_collected(0),                                                             
    report_replayed(1),
    report_dropped(2),                                                              
    hpke_unknown_config_id(3),
    hpke_decrypt_error(4),
    vdaf_prep_error(5),
    batch_saturated(6),
  } ReportShareError;
```

1. Does anyone have a strong preference for dashes? 
2. Does anyone object to landing this in DAP-02?

**Comment by tgeoghegan** [comment]
1. No. The argument for consistency with RFC 8446 is good enough for me.
2. I think we could take this in draft-02 if we really wanted to, but since this change has no actual impact on implementations (the enum variant names never appear in encoded messages), I think we could err on the side of allowing a reasonable span of time for discussion in the WG and do this in draft-03.
