### ISSUE TITLE
Consider tying nonces to shares within a batch.

### ISSUE THREAD

**Issue by hannahdaviscrypto** [ietf-wg-ppm/draft-ietf-ppm-dap#316]
DAP uses a checksum over the report nonces to make sure that the same set of reports are included in repeated batches, but it does not verify the consistency of the ciphertexts  and input shares themselves between collect requests. In situations where max_batch_lifetime >=2, it may be possible for a a malicious leader to change the input share for a given nonce between two collect requests over the same batch interval. Replays are currently prevented by putting the nonce in the AAD of HPKE for client reports; however this does not protect against nonce replays with changed input shares by malicious clients. This could be of particular concern for Poplar, where multiple collect requests are used to explore a binary tree that is expected not to change between aggregations. 

Could we consider additional verification strategies for honest aggregators/helpers to ensure that every repeated batch interval contains the same input shares as well as the same nonces?

**Comment by tgeoghegan** [comment]
This is a really neat attack. I think this would be mitigated if we wind up doing direct uploads from client to helper (tracked in https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/130). But unless there's some kind of authentication scheme in play, a leader can still race with the clients to submit reports with the same nonces but different contents, so I wonder whether this falls into the general category of Sybil attacks?

**Comment by hannahdaviscrypto** [comment]
Yes, I think direct uploads would absolutely solve the problem. 

I think this is definitely related to Sybil attacks but goes slightly further because the leader can replace honest reports or change malicious reports after they have already been collected one or more times in addition to its expected ability to impersonate arbitrary clients at the start of the protocol.

**Comment by cjpatton** [comment]
An alternative to direct uploads is to ensure the input shares are sent precisely once (and not resent with each AggreagteInitializeReq). This would also go part of the way towards addressing #130, since it reduces communication cost by a factor of `max_batch_lifetime - 1`.

**Comment by simon-friedberger** [comment]
> Replays are currently prevented by putting the nonce in the AAD of HPKE for client reports; however this does not protect against nonce replays with changed input shares by malicious clients.

**First**, there is definitely something fishy in the spec regarding nonces.
IMHO the leader can just discard reports with a repeated nonce but it's indeed not clear:

> _To detect replay attacks, each aggregator keeps track of the set of nonces pertaining to reports that were previously aggregated for a given task. If the leader receives a report from a client whose nonce is in this set, it either ignores it or aborts the upload sub-protocol as described in [Section 4.3](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#upload-flow). A Helper who receives an encrypted input share whose nonce is in this set rejects the report as described in [Section 4.4.1.4](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#input-share-batch-validation)._

What is this doing: "previously aggregated for a given task"? Shouldn't nonce repetition just be forbidden?

ISTM that the client is sending a report once hence a nonce against replay makes sense. But, if the helper is receiving  shares multiple times, a nonce isn't doing it's job anymore.

**Second**, it's not clear how the actual batch validation is supposed to work:

> [4.5.6. ](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.5.6)[Batch Validation](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#name-batch-validation)
> 
> Before an Aggregator responds to a CollectReq or AggregateShareReq, it must first check that the request does not violate the parameters associated with the DAP task. It does so as described here.

Note that the `CollectReq` goes to the leader who should be able to just discard repeated nonces and the `AggregateShareReq` goes to the helper but it doesn't actually contain the shares. Those had been sent with the `AggregateInitializeReq`. So something needs to be fixed here.

**Comment by simon-friedberger** [comment]
I would propose that we change the nonce usage to:
"[...] each aggregator keeps track of the set of nonces it has previously received, for the currently valid reporting period. If it receives a report whose nonce is in this set, [...]". The part about the currently valid reporting period allows throwing away the list of nonces at some point.

This implies Chris' proposal of sending input shares only once.

**Comment by branlwyd** [comment]
> What is this doing: "previously aggregated for a given task"? Shouldn't nonce repetition just be forbidden?

The original text ensures that nonces only need to be unique inside of a task. While nonces _should_ be universally-unique (assuming clients construct them properly, i.e. by reading bytes from a CSPRNG), I'd prefer if the spec text only required aggregators to look for conflicts within a given task. (i.e. tasks should be _isolated_ from one another)

I do like the idea of allowing us to "forget" report nonces after awhile. The spec currently allows for this: aggregators can drop uploads that are too old (or for any other reason). Since the identifier of a report effectively includes the timestamp, this means aggregators can forget nonces that are attached to timestamps that are "too old". I think a similar argument would work for `fixed-size` tasks. (though I wonder if some of the wording around this was blurred with the introduction of `fixed-size` tasks, which split the timestamp out from the nonce)

===

> Second, it's not clear how the actual batch validation is supposed to work

The referenced "batch validation" section covers validation of batch parameters (number of reports, batch boundaries), and is evaluated during collection to ensure the batch being collected meets all of the requirements. Note that none of the checks require knowing the shares, only how many shares there are (and other information like batch parameters & task configuration).

Nonce replay protection is described in the [Anti-replay](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#name-anti-replay) section, and I believe it is referenced from appropriate places such that the aggregators have all the information they need to evaluate the protection.

**Comment by tgeoghegan** [comment]
@simon-friedberger I submitted https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/pull/333 last week to cover the missing text about the leader rejecting duplicate nonces during the upload protocol.

**Comment by simon-friedberger** [comment]
@branlwyd 

> The original text ensures that nonces only need to be unique inside of a task. 

Ah, that's fine. I thought there was something more to the statement, e.g. "previously aggregated" not necessarily meaning "received" but that they have been used in an aggregation.

> > Second, it's not clear how the actual batch validation is supposed to work
> 
> The referenced "batch validation" section covers validation of batch parameters (number of reports, batch boundaries), and is evaluated during collection to ensure the batch being collected meets all of the requirements. Note that none of the checks require knowing the shares, only how many shares there are (and other information like batch parameters & task configuration).

It also includes the "overlap check":

> _Finally, the Aggregator checks that the batch does not contain a report that was included in any previous batch. If this batch overlap check fails, then the Aggregator MUST abort with error "batchOverlap". For time-interval tasks, it is sufficient (but not necessary) to check that the batch interval does not overlap with the batch interval of any previous query. If this batch interval check fails, then the Aggregator MAY abort with error "batchOverlap"._

I assume this is also based on the nonce. Correct?

@tgeoghegan 

> @simon-friedberger I submitted #333 last week to cover the missing text about the leader rejecting duplicate nonces during the upload protocol.

Seems reasonable, can we do the same for the helper?

**Comment by branlwyd** [comment]
> I assume this is also based on the nonce. Correct?

I think this check actually doesn't require inspecting any particular nonces -- for `time-interval` tasks this is effectively checking that there is no overlap with the time intervals in previous collect requests[1]; for `fixed-size` tasks I think things are even simpler, there is no overlap condition since batches are arbitrarily identified & the mapping of reports to batches is controlled by the aggregators.

The wording "checks that the batch does not contain a report that was included in any previous batch" is somewhat unclear, though -- it could be fairly understood as saying that checking nonces is required, even though the particulars of how this check is implemented does not require examining nonces. Maybe a clarification is in order?

[1] Though as the text notes, this is a sufficient but not necessary condition -- an aggregator implementation could also do a more precise check, allowing overlap in collect intervals as long as the overlapping portion of the intervals does not contain any reports. Determining if the overlapping portion of the intervals contains any reports would indeed require checking individual reports' timestamps, which is similar to having to check nonces. However, I'm not sure of a practical reason an implementation would want to do this.

**Comment by cjpatton** [comment]
At IETF 118 I volunteered to implement multi-collection and resolve all related open issues.
