### ISSUE TITLE
s4.4.1.5: agg_id

### ISSUE THREAD

**Issue by seanturner** [ietf-wg-ppm/draft-ietf-ppm-dap#328]
Is there any reason that agg_id values can't match the rest of the document? In agg_id, leader is 0x00 and helper is 0x01, but everywhere else it's 0x01 and 0x02 for leader and helper, respectively.

**Comment by tgeoghegan** [comment]
This is an impedance mismatch between the roles defined by DAP and the roles defined by VDAF. VDAF doesn't really have a notion of a client or a collector, and so the only roles are the aggregators, who get numbered from 0.

In DAP, we have those two additional roles, and the role identifiers are used in HPKE encryption, among other places. We could have used leader = 0, helper = 1 in DAP to line up with VDAF, but we decided to put the aggregators at the end of the role enum so that if we allow more aggregators at some point, their IDs will be continuous with the two existing ones.

At some point we'll have to make a decision about whether DAP will ever support more than two aggregators. Even if it does, that protocol may not be backward compatible with this DAP for myriad reasons, at which point reassigning the role IDs is a minor disruption.

**Comment by cjpatton** [comment]
I'd be fine with re-assigning IDs. Another option would be to define `agg_id` to be `role - 2` or something so that we define the variable exactly once.

**Comment by branlwyd** [comment]
Another suggestion to resolve this impedance mismatch:

Currently the concept of "roles" are used for two purposes:
(a) determining the source or destination of a given HPKE-encrypted message
(b) mapping to an `agg_id` for relevant VDAF operations

Notably, (a) requires being able to represent non-aggregator roles (i.e. client/collector), while (b) only requires that aggregator roles be represented.

We could instead:
(a) assign each aggregator an `agg_id` value (e.g. leader = 0, helper = 1); this value is used directly for VDAF operations.
(b) encode the HPKE role as a potentially-multibyte value. (e.g. aggregators are `0x00 || agg_id`; client is `0x01`; collector is `0x02`).

The upsides, as I see them, are that we avoid arbitrary math like `agg_id = role - 2`, and we can easily extend to more than two aggregators should we wish to in the future.

More opinionatedly, in my experience as an implementor, there are many places where a generic "role" (leader/helper/client/collector) is specified where actually we want to specify an aggregator (leader/helper). An implementation can avoid some unnecessary error-handling by splitting "role" from "aggregator-specific role". It might therefore make sense to take a similar strategy at the design level.

The most obvious downside is that we possibly use an extra byte for roles during HPKE encryption; I think this is marginal since the role is part of the (implicit) `info` parameter, i.e. this extra role byte does not translate to an extra ciphertext byte. I think it's OK to use a variable-length encoding here w/o risking an ambiguous message as the message is still unambiguously parsable, but please check this assertion.

**Comment by cjpatton** [comment]
Just to reiterate a requirement discussed on pr #335: We can't change the value of agg_id passed to VDAF.prep_init() without breaking compatibility with VDAF-03. In particular, for the leader this value MSUT be 0 and for the helper this value MUST be 1.

If you feel like VDAF needs to be designed in a way that makes this *not* a breaking change, please follow up on https://github.com/cfrg/draft-irtf-cfrg-vdaf/issues/40.

**Comment by cjpatton** [comment]
Now that we've settled on two Aggregators for DAP, I think the delta here is primarily superficial (To match the VDAF spec, we'd change 2 -> 0 and 3 -> 1.) I'm gonna close this issue, but I suppose if anyone feels strongly about aligning these things, please send a PR and I suspect we'd merge it.
