### ISSUE TITLE
DAP-02 has stricter anti-replay requirements than DAP-01

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#362]
Anti-replay is enforced in [Section 4.4.1.4](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.4.1.4). Both DAP-01 and DAP-02 read:

> Check if the report has already been aggregated with this aggregation parameter. If this check fails, the input share MUST be marked as invalid with the error report_replayed. This is the case if the report was used in a previous aggregate request and is therefore a replay.

What's not fully specified, at least in this section, is what it means for a report to "have been aggregated (with this aggregation parameter)". For that we have been referring to the anti-replay section. [DAP-02, Section 4.5.7](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-02.html#name-anti-replay) reads:

> To detect replay attacks, each aggregator keeps track of the set of report IDs pertaining to reports that were previously aggregated for a given task.

The report ID is defined as

```
uint8 ReportID[16];
```

On the other hand, [DAP-01, Section 4.4.6](https://www.ietf.org/archive/id/draft-ietf-ppm-dap-01.html#name-anti-replay) reads:

> To detect replay attacks, each aggregator keeps track of the set of nonces pertaining to reports that were previously aggregated for a given task.

The nonce is defined as

```
struct {
  Time time;
  uint8 rand[16];
} Nonce;
```

Thus in DAP-01 we are required to check for collisions of the timestamp+random value, whereas in DAP-02 we are required to check for collisions of just a random value (report ID). The latter is stricter, since it disallows repeated random values.

After discussing some implementation stuff with @MichaelScaria, I realized that this may have been an unintended regression. From a security standpoint, I think the DAP-02 requirement is better, since it forces the client implementation to generate a fresh report ID each time it generates a report. Otherwise it is easier to fingerprint reports from the same client. 

Does this violate assumptions in anyone's implementation? Where I can imagine this being problematic is if your implementation currently shards nonce sets into time windows. [Daphne 0.1.2](https://crates.io/crates/daphne) does this, but we have to amend this behavior to implement fixed-size queries anyway.

Reply to this thread if this causes an issue for you and you think we should reconsider this requirement.

**Comment by branlwyd** [comment]
From Janus' perspective, I think we are OK with this change.

Janus also breaks report sets into time windows -- I don't think this change will affect Janus' implementation of that functionality, though as you note this sharding behavior will change with `fixed-size` tasks.

**Comment by MichaelScaria** [comment]
Seems fine to me. I can't think of a reason why the client would want to reuse a reportID with a different time for the same task.

**Comment by bhalleycf** [comment]
I am in favor of recommending that clients generate a good random id for every report AND for allowing the timestamp to be considered as part of the anti-replay strategy.  While an unbounded memory of seen report ids would indeed be excellent protection, in practice this requires unbounded storage of report ids, which is a practical problem for implementations.

Replay of a client report can leak information, so we want to assure that a report is aggregated at most once.  A report has a report id and a timestamp, both generated by the reporting client.  Both are included in the authenticated additional data, and cannot be altered without the tampering being evident.

For the rest of this note, we will assume that the client is doing its part for its own privacy by choosing a new random report id for every report, and by having a clock is not hugely inaccurate.  Even if the clients are doing their part, we must still be concerned with the actions of other entities, such as a compromised leader, helper, or collector.  We also need to prevent third party manipulation, e.g. by replaying captured reports.  The use of the timestamp can help us here, because the timestamp cannot be altered by any of these parties without detection.  If at least one aggregator is honest and imposes the policy below, then we can use the timestamp to ease our storage burdens.

Let’s consider the timestamp in more detail.  For reporting accuracy we don’t want to permit just any timestamp to be aggregated.  At any given time T by the server’s clock, there are bounds we want to apply based on the timestamp.  Reports earlier than some time MinTime = T - MinDelta should be rejected as too old, and reports farther in the future than MaxTime = T + MaxDelta should be rejected for being so confused about the time.  We allow reports slightly in the future as we want to allow for clock-skew.  Call the closed interval [MinTime, MaxTime] for time T Allowed(T).

```
                      Allowed(T)
Too Old [------------------------------ T --] Too Far In the Future
        ^              	                    ^
        T - MinDelta                        T + MaxDelta
        MinTime                             MaxTime
```

We will discard reports outside of this interval when we receive them, and also when we process them.  We impose the “on reception” policy to avoid queuing work that we’d never do, and we impose on processing to prevent backlog and to allow the definition of LeastRetainedTime (below).

Assume a monotonically non-decreasing system clock.  Whenever an aggregation begins, we durably record the current MinTime and associate it with the active state for the aggregation job, using appropriate locking in concurrent implementations.  Define the LeastRetainedTime as the minimum of the current MinTime and the recorded MinTime over all active aggregation jobs (if any).  It is impossible to aggregate any report before this time, as it will be rejected in any new job and isn’t present in any existing job.  Garbage collection may safely remove any recorded report metadata with a timestamp before the LeastRetainedTime.
We now only have to remember report ids that are greater than or equal to the LeastRetainedTime.  If clients choose random ids with every report submitted, and there is at least one honest aggregator, then any given report cannot be replayed.

Note that in cases where a server is so flooded with reports that it cannot process or remember them, then the DAP spec still has the "report_dropped" error available to ensure that reports are not aggregated when anti-replay cannot be assured.

**Comment by cjpatton** [comment]
Thanks @bhalleycf. Full disclosure: Bob is helping out with Daphne development. When he showed me this analysis, I was pretty convinced that relaxing this requirement would be safe and worth it to reduce burden on implementations. Although I'm not strongly opposed to keeping the stronger requirement if folks think it is useful.

I think the only change that would need to be made is to ["Anti-Replay"](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.5.7):

> To detect replay attacks, each aggregator keeps track of the set of ~report IDs~ **(report ID, timestamp) pairs** pertaining to reports that were previously aggregated for a given task

**Comment by tgeoghegan** [comment]
I also agree with Bob's analysis. I think we should make the change described by cjpatton [here](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/issues/362#issuecomment-1304345127) in DAP-03.

**Comment by branlwyd** [comment]
This argument is good. One point: while it certainly justifies including the timestamp in the overall anti-replay strategy, it does not necessarily justify checking `(report_id, timestamp)` rather than only `report_id` for the ID-based check. That is, the overall strategy could be:

1. Check the timestamp; if it's out of the acceptable window, fail due to too old/too new.
2. Check if `report_id` [or `(report_id, timestamp)`] is in the set of received reports; if it is, fail due to replayed-report.

I would have a slight preference for doing the ID-based check on `report_id` only, since the report ID is the primary identifier of the report, but plausibly implementations may want to check timestamps as well (for example, if they bucket report IDs by timestamp).

Perhaps we could phrase things such that either implementation is allowed? In practice, as long as the report IDs are properly generated as random values, the timestamp will be irrelevant to the ID-based check. If the leader/helper disagree on whether to check `report_id` or `(report_id, timestamp)`, the more restrictive check will be the one that is effectively in place.

**Comment by cjpatton** [comment]
> @branlwyd edit: another way of looking at this argument -- for the ID-based replay check, what justification is there for checking (report_id, timestamp) over, say, (report_id, extensions) or (report_id, public_share)?

I think if we assume that honest clients always choose their report ID at random, then any anti-replay check that includes the report ID ought to be sufficient. I agree we could write this in a way that makes this implementation-specific perhaps suggesting that (report_id, timestamp) is one particularly useful relaxation.
