### ISSUE TITLE
Consider removing draft version from hardcoded strings like "dap-02 input share"

### ISSUE THREAD

**Issue by wangshan** [ietf-wg-ppm/draft-ietf-ppm-dap#376]
The current text use some magic strings when calling `SealBase`, for example in [upload request](https://github.com/ietf-wg-ppm/draft-ietf-ppm-dap/blob/main/draft-ietf-ppm-dap.md#upload-request)

```
enc, payload = SealBase(pk,
  "dap-02 input share" || 0x01 || server_role,
  task_id || metadata || public_share, input_share)
```

This assumes backward incompatibility across drafts, but it is plausible to have two or more drafts only contain backward compatible changes, especially if the client side of the protocol become more stable. Therefore it's better to remove "dap-02" from the string so the draft version is not hardcoded when calling SealBase, give client, leader, helper implementation a chance to use backward compatible draft versions. We can always change other part of the string to force backward incompatibility if needed.

**Comment by cjpatton** [comment]
Breaking backwards compatibility is very much the point: If there is a security vulnerability in DAP-X, then we want to make sure we can migrate to DAP-X+1 without allowing the attacker to force fallback to the previous version.

I'd be open to only changing this as needed, as you suggest, but I think it would be better to plan your implementation so that you can upgrade as needed. In Daphne we have built a versioning mechanism that, when needed, will allow us to support multiple versions simultaneously.

**Comment by tgeoghegan** [comment]
I agree with Chris. We could introduce the notion of a "security epoch" and use that instead of the draft version, but then we'd have to decide every time we release a draft whether the changes are sensitive enough that it warrants bumping the epoch. That is a chore at best, and I suspect we'd wind up bumping the epoch every single time just to be safe anyway.

**Comment by wangshan** [comment]
I get the motivation, but we can still achieve that by changing the string from something like "dap input share" to "dap input share X+1" on all participants when such vulnerability is detected, as long as one party is honest, even if all other parties refuse to upgrade, no privacy leak can happen.

Alternatively, how about let these strings (or at least the one for input share) to be set as part of AAD, so the task creator can decide what the string should be.

**Comment by ekr** [comment]
I agree with Tim. At some point in the future, we might be moving slowly enough that we want to keep the strings the same, but that seems like a future problem.

**Comment by wangshan** [comment]
Closing this since the overwhelming response is to keep the draft version
