### ISSUE TITLE
Aggregation phase naming

### ISSUE THREAD

**Issue by simon-friedberger** [ietf-wg-ppm/draft-ietf-ppm-dap#384]
We currently have AggregateInitializeReq/-Resp and AggregateContinueReq/-Resp containing the word "Aggregate" even though no aggregation is performed in these steps. In some places we also speak of verification, the VDAF draft calls it simply preparation.
"Verification" would also be a natural choice. VDAF chose preparation because of the option to have a non-V DAF and because other tasks, like format conversion, are included as well.

We might want to adopt the term preparation as well. 

I've started a draft of a report flow here which might help with the discussion:

![image](https://user-images.githubusercontent.com/103195467/204466721-96bd7139-c1a7-42e1-b91f-d9e9b3d0b054.png)

[Editable Source](https://sequencediagram.org/index.html#initialData=A4QwTgLglgxloDsIAIDCAbKBTJAoUks8ISyAMliACZZj7jRyIoASW6wt9hTJKqAe3TosMCALq4wAIwEAPZAIButNJhwQAXAFlKAZwCuYLAFsNybbgzYkAWgB81jZoDKwTBCmyFy1U6SuAPoAjAAU2gCUADQugQBM4RFW6naOKVoAoggwYACewJ4y8ooqYGo2mdmBFNShsWGR0VkwgWwcdfGJSf4QDjU0YJoAqu4C1MgASljAEp64AMQAvIv9qgAWIHrIIMh6WCgCAGbIxjOQWyRUyADufFviuxAMyMCn4CDQAgjLuN4lqqtBoDkBsLrt9opjqdZnoADoIS43O7IB56J6QF5vMAfKBfXBYOSIKggaQiQBIRMh5pgAOZrCDU7G5ZAABSxOK+LNBWFwgL6lAGmgAIqI8gVkM1qvyOg0ItFkEoQJhiRAsMh0AIYIr0LkosgoAgoCgAGqCgCCADEefzaA42pxBqbqQysNSPlgAJIG6CKqAALywUwAjgYsGi9dl0AYqPrqeKqnaOglGrgQGIoAqVcg7Vxs2Bbex7UKRfkUBL+tKurqFUq3WqNVqdeHDcgTRbcLm+dRaJpHc7XSrPYaoD7-VM9MBcDRU9AM6rc7hcAIxdRo58EehMdN3muTgIDAgqHpdadKCqqFau3n7IDNMzaIcJCZkAgCShXlvsTu0dMLwN8xxu17Yx+ywQQkH1EMgxTNNZyzAsc3gq9c1ve9H2fV9NwIdkEEeH8O2va0HSdYC3TA6AEEg0MJynGDa3nHBz3xA8FwJIkSXJSkaTpBkQCZJc10VFljFsICXWw35il8MpASiZD3WOCA1lVJ49AAa22YQBGuLZ31sEBiLE8jY2hc5w3EeFpAMGBVP2I8USUtVCO2A8QUQ5BNRwxVjGoJkqAEeyPgAOnhd0UGMYMoGMLYEH8mABBMEx91gbDdU2OsEFjNK1i0lEBHhGhDn1ZSHMs6zbL1HTniOezlM2VTAu4LV2F-G0CMvHsDJAk5phhMz-NKmyID0dtEP-QtRK6kyhr65ABtsxrhHYSFDiYxjWMudisFsTioFpelGTQIQRDTDlmS5KwjtEcQrxvQRFrEKDp3TWtARam7CM0VAlOs7rg1DFBqygVdcje2wHDu47rs0ABmAAGaHcuQAArARpGQIYJndaCZ1rCGrokSkeJBv4pMO+6obxsQCZmYQthRtGMax-FCQ20ksApKldu4g6JuwzlNm5Xl7GQ3mVRcDZjCg7Hnszed8JvUWsHF8AAyoydKFo2XENW0HHEuqnBlCGmRCoCIychsdqI1nHM1emibdVSnrpYg8gA)

**Comment by tgeoghegan** [comment]
Yes, this awkwardness in naming has been around for a while. It's tempting to reach for a term like "aggregation", except that suggests a function that takes _n_ items and produces 1. However, VDAF uses preparation to mean the transformation of a single input share into an output share, and then aggregation is reducing _n_ output shares to a single aggregate. We've also talked about using "verification", but unfortunately that verb isn't correct in all cases. In particular, the VDAF draft also defines DAFs, which drop the MPC zero knowledge proof verification (this is intended for settings where strong client authentication or attestation provides sufficient confidence in the integrity of input shares).

What I do agree with is that DAP needs more explanatory text explaining what reports, aggregate shares and aggregate results are, and what the lifecycle of each of these things is. This is particularly awkward because the VDAF [preparation](https://cfrg.github.io/draft-irtf-cfrg-vdaf/draft-irtf-cfrg-vdaf.html#name-preparation-2) and [aggregation](https://cfrg.github.io/draft-irtf-cfrg-vdaf/draft-irtf-cfrg-vdaf.html#name-aggregation-2) steps both get run by DAP's aggregation sub-protocol, which is definitely confusing. I'm not sure that reaching for another synonym of "aggregate" would be less confusing, though.

**Comment by simon-friedberger** [comment]
Would you agree to the definitions in my diagram then?

As it stands, the aggregation sub-protocol ([4.4](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#name-verifying-and-aggregating-r)) does _both_ verification and aggregation. And the collection sub-protocol ([4.5](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#name-collecting-results)) does _both_ aggregation and collection.

So we split Aggregation into Preparation and Pre-Aggregation and make the Aggregation part of Collection explicit.

I think this makes things less confusing because the pre-aggregation in the current Aggregation Sub-Protocol is only an optimization. So by splitting it, we don't have to use the name aggregation for things that possibly don't aggregate.

**Comment by wangshan** [comment]
I agree the names are very confusing. I'm not sure Pre-aggregation should have its own flow, because it's not part of a sub-protocol.

> We've also talked about using "verification", but unfortunately that verb isn't correct in all cases. In particular, the VDAF draft also defines DAFs, which drop the MPC zero knowledge proof verification

Verification can still make sense for DAF, since helper needs to open the sealed report, if that can be counted as "verify". Preparation works too, but I wonder if we should keep DAP flow names and VDAF step names de-coupled so both can evolve without worrying about violating names in the other?

**Comment by chris-wood** [comment]
Given alignment on top of VDAF and the points @tgeoghegan raises above, I'm going to close this out on the basis that it's editorial and we don't have any better options at the moment.
