### ISSUE TITLE
Decoupling the aggregation parameter from aggregation jobs

### ISSUE THREAD

**Issue by tgeoghegan** [ietf-wg-ppm/draft-ietf-ppm-dap#405]
Currently, the leader transmits aggregation parameters to the helper in an `AggregationJobInitReq`. Servicing a collection request can require arbitrarily many aggregation jobs (the leader chooses how many jobs to schedule), but all of them will have the same aggregation parameter value. This is fine for Prio3, because there is no aggregation parameter and thus it takes up no space in the wire message. But if a VDAF happens to have a large aggregation parameter (as is likely to be the case for Poplar1), then it's wasteful to retransmit the exact same aggregation parameter many times.

**Comment by tgeoghegan** [comment]
One way forward here would be to add a new resource on the helper for aggregation parameters. So the leader would do something like:

~~~
PUT /tasks/{task-id}/aggregation_parameters/{agg-param-id}
~~~

An `agg-param-id` would be a 16 byte unique identifier. The body of the request would contain `opaque agg_param<0..2^32-1>;`. Then, instead of having `agg_param` inline in `AggregationJobInitReq`, we would have:

~~~
struct {
  boolean has_agg_param;
  select (has_agg_param) {
    case true: AggregationParameterId agg_param_id;
    case false: Empty;
  };
} AggregationParameterSpecifier;

struct {
  AggregationParameterSpecifier agg_param;
  PartialBatchSelector part_batch_selector;
  ReportShare report_shares<1..2^32-1>;
} AggregationJobInitReq;
~~~

Maybe we could also include an affordance for specifying an aggregation parameter value inline in `AggregationParameterSpecifier`.

**Comment by branlwyd** [comment]
If we go this route, I think we should indeed allow specifying an aggregation parameter value inline, rather than special-casing on whether the VDAF has an aggregation parameter or not. This would be more flexible/general than special-casing on whether the VDAF has an aggregation parameter, without requiring more code complexity or bytes-on-the-wire. (and it would remove any possible error cases where `has_agg_param` is specified incorrectly)

That is, something like:
```
enum {
  immediate(0),
  by_ref(1),
} AggregationParameterSpecifierType;

struct {
  AggregationParameterSpecifierType type;
  select (type) {
    case immediate: opaque agg_param<0..2^32-1>;
    case by_ref:    AggregationParameterId agg_param_id;
  };
} AggregationParameterSpecifier;
```

**Comment by cjpatton** [comment]
@branlwyd: SGTM!

@tgeoghegan: One question the resource's scope: Is scoping by task sufficient? One thing that we have to be careful about is that we don't want to hold onto aggregation parameters longer than we absolutely have to. In the case of Poplar1, the prefix tree leaks more information about the measurements than the heavy hitters do. At the very least I think we'll need to include some language about expiring this resource.

**Comment by tgeoghegan** [comment]
I don't think there is any narrower scope we could attach an aggregation parameter to. The only thing that would make sense is an aggregate share, but it's not guaranteed that an aggregate share will have been created by the time the leader starts scheduling aggregation jobs (otherwise you can't do eager Prio3 aggregation).

I agree that some language about when aggregation parameters can be safely discarded is needed, but I'm not sure what threat you're describing. Are you concerned about a malicious aggregator leaking aggregation parameters to attack privacy? But if the aggregator is malicious, wouldn't it just ignore protocol language about discarding aggregation parameters?

**Comment by cjpatton** [comment]
I'm not really describing an attack in our current threat model. This is more about defense-in-depth: intermediate aggregation parameters *are* leaky with respect to the batch of measurements (this is a well-known limitation of using IDPFs for heavy hitters), so we want to treat them as somewhat toxic assets. As an analogy, you wouldn't want to store plaintext input shares indefinitely, in case your server ever gets compromised.

**Comment by tgeoghegan** [comment]
I think this change is too ambitious for draft-ietf-ppm-dap-05, given the July 10 deadline. On top of that, the key motivation is Poplar1, and none of the DAP deployments I'm aware of have immediate plans to deploy that VDAF. Let's tackle this a little later.

**Comment by cjpatton** [comment]
At IETF 118 I volunteered to implement multi-collection and resolve all related open issues.

**Comment by cjpatton** [comment]
This change would require higher storage requirements and would add a bit of protocol complexity. (For instance, the aggregation parameter might arrive after an aggregation job.) Also, for heavy hitters, the aggregation parameters are privacy sensitive, so implementations would need to come up with a plan to prune aggregation parameters from storage after they're no longer needed.

The decision point is really whether the cost of re-transmission is so high that adding this complexity is worth it. Unfortunately, the cost here depends on the distribution of the inputs, since [the tree traversal depends on how many inputs have prefixes in common at each level of the tree](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-vdaf#section-9.3.1-2).

That said, we can estimate this cost by generating synthetic batch and computing the prefix tree for it. We have done so here: https://github.com/divviup/libprio-rs/pull/956

Using the same parameters as the performance analysis in the [Poplar paper](ia.cr/2021/017), we find that the largest aggregation parameter is about a kilobyte. Moreover, adjusting the size of the batch doesn't change this much: even for 100K measurements, the distribution doesn't change much.

Even planning for an aggregation parameter that is 10x larger, the cost of re-transmitting with each aggregation job is easily outweighted by the cost of this change.
