### ISSUE TITLE
Replay attack requirements could be tighter

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-ppm/draft-ietf-ppm-dap#442]
It looks like the entirely of the replay protection requirements are buried in an implementation note in [Section 4.4.1.4](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.4.1.4-3.6.4.1).  The text here is pretty terse, so even though it is probably a good cue to someone who understands the problem pretty well, there are lots of bits missing:

1. Normative language.  (Maybe this is covered by [this paragraph](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.4.1.2-2), but that is also buried.)
2. An explanation of the attack that this covers.[*]
3. Discussion of the use of timestamps, clock skew, and the associated trade-offs.

This probably justifies a section of its own.

[*] Replay attack mitigation wouldn't be necessary if you submit the data directly (and don't retry failed uploads ... and avoid using TLS early data).  Therefore, honest clients that submit data directly to the leader are only exposed to the possibility that the leader defects and replays the submission.  So maybe only helpers need to perform validation under this architecture.

**Comment by tgeoghegan** [comment]
Martin wrote this issue against DAP-04. Section 4.4.1.4 is now [4.5.1.4 Input Validation](https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-08#name-input-share-validation).

There are lots of references to 4.5.1.4 Input Validation from sections of normative text that specify the upload, aggregation and aggregate share sub-protocols. I believe we did this so that the document would have one canonical description of how to validate input shares, but it seems that the indirection is confusing to at least Martin (whose sense of what makes a good standard ought not be ignored), and even as an author, I find it difficult to decide how 4.5.1.4's language -- which is written in terms of an aggregator preparing inputs -- applies to the upload protocol.

I think the path forward here is to break up 4.5.1.4 and "inline" its normative text into the different sections that currently refer to it. Then the upload section could explicitly discuss what should be done during that sub-protocol instead of making implementers reason through which parts of 4.5.1.5 are relevant. The downside is that we'd be duplicating some information (e.g., across the leader and helper descriptions of input validation) and admit the risk of disagreement between sections.
