### ISSUE TITLE
Batch selection as Collector-Leader buisness logic

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#519]
DAP requires some means of partitioning reports into batches (batch selection) such that the Leader and Helper agree on which reports go into which batch. Many strategies are possible. We formalize these as different "query types", of which there are currently two:

1. "Time-interval": Collector specifies a time interval and the Aggregators aggregate all reports with timestamps that fall in that time interval.
2. "Fixed-size": The Leader maps reports to batches identified by distinct "batch IDs" by any strategy it wishes. (The Collector has no control over partitioning, at least in the core DAP protocol.) 

Supporting multiple query types adds complexity for implementations. For example, for Time-interval, we don't know which batch a report corresponds to until collection time. For Fixed-size, we already know at aggregation time: it corresponds to the batch ID sent by the Leader at the start of the aggregation job. This makes an implementation of a fixed size queries much easier because it we always know where to store output shares and report IDs.

The requirement we're trying to satisfy by supporting multiple query types is to give the Collector some degree of control over how reports are partitioned.

(Aside: There is another benefit, but we haven't been able to articulate it very well. Fixing the query type to the task config gives the Client some assurance about how its report is used: for Time-interval in particular, the Client knows it will always be aggregated with reports generated around the same time. This seems like a nice property to have, but it's hard to say why. It doesn't seem necessary for our core privacy consideration.)

Given the implementation complexity, we (Janus and Daphne maintainers) would like to ask if anyone who actually cares about this requirement. Observe that Fixed-size is general enough to support a variety of batching strategies, so long as the Collector and Leader have some out-of-band mechanism for implementing it. In other words, we could view batch selection as "business logic" that is not part of the core protocol.

Of course, another option is to do nothing and emphasize that an implementation is free to ignore query types it doesn't want to implement. In particular, Daphne and Janus could just drop Time-interval support and optimize for Fixed-size.

What do folks think we should do here?

We have discussed this in the past. I think this is the first thread on the list about this: https://mailarchive.ietf.org/arch/msg/ppm/NKPIIm5HvZ1p8EkS3tmwj6DBXDs/

**Comment by branlwyd** [comment]
As a maintainer of Janus, I support the removal of the time-interval query type.

A few points:
* We implemented removal of the time-interval query type as an experimental change to Janus. This reduced code size by about 10%, build times by about 20%, and test runtimes by about 25%.
* Implementing the protocol is simplified in several ways:
  * The Collector no longer needs to know how to collect larger & larger intervals until it finds a time interval with at least `min_batch_size` reports. I suspect that this behavior would be a significant corner case for many realistic deployment scenarios.
  * Similarly, Aggregators no longer needs to implement the ability to collect across multiple contiguous time intervals when requested to do so by a Collector.
  * Janus would be able to remove 100% of its interval-indexing (e.g. looking up entities like aggregation/collection jobs by intersection of some interval associated with the entity with a given timestamp or interval). This likely implies that implementations would no longer require interval-indexing, allowing use of simpler "scalar" indexes, which may enable use of a wider variety of datastore technologies without potentially requiring implementation of interval-indexing. In particular, since only "scalar" indexes are required, this may ease implementation on key-value datastores.
* We implemented a business-logic feature called "time-bucketed fixed-size", which causes our Leader to generate fixed-size batches such that all reports in each batch are in the same "time window", similarly to how the time-interval query type groups all reports in the same "time window" into the same batch. This gives confidence that the fixed-size query type can support use-cases currently supported by the time-interval query type. Much more detail below.
  * This approach effectively allows the reports in each time window to be collected incrementally (up to the batch size). This usually requires more collections by the Collector per time window. But this also allows collection of reports for as long as reports are arriving for the time window: one downside of the time-interval query type is that once Collection has occurred for a given time window, any late-arriving reports will effectively be discarded; the fixed-size query type does not share this downside. We are aware of at least one DAP user interested in significantly backdating their reports, and who have expressed interest in keeping the "long tail" of reports.
  * This "incremental" reception of aggregate values for each time window allows collection to occur more eagerly, which may enable DAP users who wish to perform analysis quickly despite having a long tail of post-dated reports.
  * One downside of time-bucketed fixed-size is that there may be up to `min_batch_size` reports which cannot be added to a batch (i.e. any grouping of reports to batches inside a given time window may leave up to `min_batch_size - 1` reports ungrouped). We've discussed tuning batch size to keep this number of reports acceptably small, or perhaps providing a "smeared" batch joining the final few reports in a given time window with a report from another time window (the smearing idea has not yet been implemented).
  * We do not yet have significant production deployment experience with this feature yet.

**Comment by wangshan** [comment]
I also support the removal of the time-interval query type.

> we could view batch selection as "business logic" that is not part of the core protocol.

What does this mean in practice? 

I think some use case may benefit from a relaxed `max_batch_size`: aggregator output a batch that is >= `min_bathc_size`, but does not abort if batch size exceeds `max_batch_size`.

**Comment by branlwyd** [comment]
> I think some use case may benefit from a relaxed `max_batch_size`: aggregator output a batch that is >= `min_bathc_size`, but does not abort if batch size exceeds `max_batch_size`.

I think this is a good idea, too. `min_batch_size` is a privacy parameter, but making `max_batch_size` optional is acceptable. A fixed-size task without a `max_batch_size` could drop some corner cases in the aggregation-job creation logic.

**Comment by cjpatton** [comment]
At IETF 118 we decided to keep the query the types they are. I've created a PR to close this issue, which clarifies that implementations are free to ignore query types they don't want to implement.
