### ISSUE TITLE
Relax Helper handling of duplicate report IDs to support retries

### ISSUE THREAD

**Issue by kristineguo** [ietf-wg-ppm/draft-ietf-ppm-dap#520]
Currently, the spec specifies that if the Helper detects any duplicate report IDs within an aggregation job, it should abort: https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-07#section-4.5.1.2-3
> Next, the Helper checks that the report IDs in AggregationJobInitReq.prepare_inits are all distinct. If two preparation initialization messages have the same report ID, then the Helper MUST abort with error invalidMessage.

If the Leader sends an AggregationJobInitReq but loses the response, it should be able to retry the same request (or even with additional new reportIds). Under the current behavior, the Helper would reject the entire request. 

We should consider dropping this requirement to support AggregationJobInitReq retries. We should only consider reports replayed if they have been previously used for _different_ `part_batch_selector`/`agg_params` (per https://www.ietf.org/archive/id/draft-ietf-ppm-dap-07.html#section-4.5.1.4-3.6.3).

Otherwise, a previously seen report ID for the _same_ `part_batch_selector`/`agg_params` should be considered a "duplicate report" and handled in a way that prevents verifying / contributing twice. For example, the Helper can store reports with the report ID as the primary key. If the Helper has previously seen a report ID, it can use the previously stored state. For new reports, it can compute the prepare responses.

Within a job, the first occurrence of a report ID can be accepted. All further occurrences within that job can be rejected as `report_duplicated`.

With these changes, the Leader can now retry a failed AggregationJobInitReq without having to lose all previously processed reports.

**Comment by tgeoghegan** [comment]
I agree completely with you that retryability is crucial. The intent is indeed that multiple requests to `PUT /tasks/{task-id}/aggregation_jobs/{aggregation-job-id}` for a given `task-id` and `aggregation-job-id` should all succeed, provided the `AggregationJobInitReq` in the body has not changed. We don't explicitly say so because it is implied by the `PUT` HTTP method.

As for 4.5.1.2-3: the intent of that paragraph is that report IDs must be unique in the scope of a single `AggregationJobInitReq` message, so I don't think it rules out retrying `AggregationJobInitReq` messages. This is about rejecting malformed messages where the same report ID appears twice and absolving aggregators of guessing which is the real report share for that report ID.

If you'd like to propose some text that makes the scope of this requirement more clear, we'd be happy to review a PR on the spec.

**Comment by cjpatton** [comment]
I see things as @tgeoghegan does here. We definitely want to make sure that, if a request is aborted, it should be safe to retry. In this particular case, the Leader should be able to retry with de-duplicated candidate set (i.e., with one of the reports with the duplicate ID removed), and the Helper shouldn't consider any of the reports replayed.

As I understand it, this problem is solvable with clarification to the text. Of course, let us know if we're missing the point here :)

One clarification: The intent of anti-replay is that a report is assigned to one and only one batch for a task. Thus we want to prevent replays even for different values of `part_batch_selector` (i.e., the batch ID). Different values of `agg_param` need to be handled according to the [agg param validity rules for the VDAF](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-vdaf#section-5.3). These rules govern exactly the type of problem you point out (preventing some report randomness from getting reused insecurely).

> Within a job, the first occurrence of a report ID can be accepted. All further occurrences within that job can be rejected as `report_duplicated`.

Here it sounds like you're suggesting a protocol change. Do you mean that the Helper should be smart enough to reject duplicated reports within the same aggregation job, rather than abort the job completely?

**Comment by kristineguo** [comment]
Thank you both for clarifying! In that case, the Helper supports idempotent requests in so far as the Leader can retry the exact same request multiple times. In these cases, since we cannot re-verify the same reports again (e.g., such as with Prio3), I'm assuming the expected behavior would be to return the Helper's stored state from the first time it processed the aggregation job.

For duplicated reports, this point makes sense to me:
> absolving aggregators of guessing which is the real report share for that report ID

I'm assuming the Helper will not have counted any of the other reports as processed if the aggregation job init is rejected, so we can retry the request with the duplicate report removed and succeed.

**Comment by simon-friedberger** [comment]
Indeed as long as no actual aggregation steps have been performed (at most until the result has been shared with the other aggregator) the report can still be used and also in a different batch. If a leader is sending multiple reports with the same ID that does seem like a bug in the leader, though. IIUC the leader is supposed to perform the same checks as the helper. This follows from the fact that ensuring that reports are not used multiple times, is necessary for protecting client privacy, so according to the security model both aggregators have to do it.

**Comment by cjpatton** [comment]
@kristineguo,

> Thank you both for clarifying! In that case, the Helper supports idempotent requests in so far as the Leader can retry the exact same request multiple times. In these cases, since we cannot re-verify the same reports again (e.g., such as with Prio3), I'm assuming the expected behavior would be to return the Helper's stored state from the first time it processed the aggregation job.

The Helper has a little leeway in how it implements things, but yeah that's one way it could work :) 


> For duplicated reports, this point makes sense to me:
> 
> > absolving aggregators of guessing which is the real report share for that report ID
> 
> I'm assuming the Helper will not have counted any of the other reports as processed if the aggregation job init is rejected, so we can retry the request with the duplicate report removed and succeed.

Correct. This can get a little tricky because there are certain failure cases where the Helper may have partially committed state changes when something goes wrong. (Think "500 Internal Error".) An implementation needs to be designed to be as resilient as possible in such cases, but the [Two General's Problem](https://en.wikipedia.org/wiki/Two_Generals%27_Problem) implies I think that something can always go wrong in theory. One way we plan to address this in Daphne is to commit to stage changes at the latest possible stage of an aggregation job.

However, this failure case is quite easy to handle fortunately. The Helper will abort the request as soon as it detects the repeated  report ID in the AggregationJobInitReq; this happens quite early in the life of the aggregation job, before there's any state changes.

@simon-friedberger ,

> IIUC the leader is supposed to perform the same checks as the helper. This follows from the fact, that ensuring that reports are not used multiple times is necessary for protecting client privacy, so according to the security model both aggregators have to do it.

Yup, that's correct.

**Comment by kristineguo** [comment]
Sounds good. Thanks both of you for your responses. It doesn't seem like any changes are required to the spec here, so will close out this issue.
