### ISSUE TITLE
Define "collection job URI" and the media type of collection polling requests

### ISSUE THREAD

**Issue by mendess** [ietf-wg-ppm/draft-ietf-ppm-dap#586]
In https://datatracker.ietf.org/doc/html/draft-ietf-ppm-dap-09#section-4.6.1-15 the draft says:
> After receiving the response to its CollectionReq, the Collector makes an HTTP POST request to the **collection job URI** to check on the status of the collect job and eventually obtain the result.

But nowhere else in the draft does it define what the `collection job URI` is. It could be reasonably inferred that it's the same URI used to initialize the collection request (`/tasks/{tasks}/collection_jobs/{collection-job-id}`) but I believe this should be better defined.

Another detail that's left unspecified is what is the media type of this request. The draft defines a media type for every request except this one.

**Comment by cjpatton** [comment]
> Another detail that's left unspecified is what is the media type of this request. The draft defines a media type for every request except this one.

@branlwyd @inahga my interpretation is that whenever we're polling, there is no payload of the HTTP request and hence no media type. Do you concur?

**Comment by branlwyd** [comment]
I agree with that -- there is no payload, and therefore no media type. Collection job polling is effectively using POST as a GET (because we view the request as having side-effects, despite otherwise semantically being equivalent to a GET request).

(Later drafts change this POST to a GET, which I think is another reason not to specify a media type for the request.)

**Comment by tgeoghegan** [comment]
Yes, we don't need a media type here because the request has no body. The "collection job URI" language is a leftover from back when leaders were free to construct arbitrary URIs for collection jobs, but we started specifying a template for those URIs somewhere along the way. We should take a change to make this more clear as suggested by @mendess.

**Comment by cjpatton** [comment]
Alrighty, it looks like we should be able to resolve this relatively easily. I'm going to move this up to draft-12.
