### ISSUE TITLE
Probing for extension support

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-ppm/draft-ietf-ppm-dap#619]
Extensions are mandatory to understand, which is a good model for something like this.
A server is required to send invalid_message if it doesn't support an extension.

If an extension (or set thereof) is ever defined that is optional, this model is not particularly friendly to probing for support.
It would be easier for client to recognize the error and try again without the optional extension
if there was an unsupported_extension message.

That sort of thing is potentially unwise if the response could be spoofed, because it would allow a leader to cause a report to be included more than once in an aggregate, but that risk seems manageable to me.

**Comment by cjpatton** [comment]
Historical note: We made the call to make extensions mandatory to implement some time shortly after draft 02. In fact, your feedback was the main decision point.

Two more notable features of report extensions:
1. They are associated with each report share, meaning each aggregator may get a different set of extensions. E.g., in some deployment you might have an extension that is only meaningful to the leader and not to a generic helper.
2. The extensions are encrypted to each aggregator: the leader can't read the helper's extensions and vice versa.

With that in mind, during the upload interaction, the Leader could decrypt, inspect the extensions, and abort if one of them is unrecognized. [Currently the spec requires a pretty opaque error in this case](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#section-4.5.2-24), but we could certainly replace this with something with more information.

That said, there is currently no way to do the same for the Helper's extensions, since the Leader can't decrypt them. Do you have a use case for this?

**Comment by cjpatton** [comment]
2024/10/24 interim: We'll resolve this by adding an abort type that the Leader can use during the upload interaction to let the Client know that some extensions aren't supported. The PR will specify an optional mechanism for conveying programmatically which extensions aren't recognized. We should also add a note in the text that there is no mechanism for the Client to probe the Helper.
