### ISSUE TITLE
@martinthomson: The Helper MUST support skew recovery

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ppm/draft-ietf-ppm-dap#626]
IIRC the language in the draft says something like: "The Leader MAY retry from the previous step; the Helper SHOULD help it recover". @martinthomson pointed out during the 2024/10/24 interim (in the Zulip) that the Leader's MAY implies a MUST for the Helper. I believe that's correct.

**Comment by cjpatton** [comment]
Specifically, in reference to [slide 7](https://datatracker.ietf.org/meeting/interim-2024-ppm-02/materials/slides-interim-2024-ppm-02-sessa-dap-and-taskprov-open-issues-00), Martin writes:

> Any MAY in a protocol is just a MUST in disguise. The entity that exercises the MAY forces other participants to do something to allow that choice. So the "SHOULD" here really needs to be a "MUST" of some sort.

**Comment by branlwyd** [comment]
I'm not sure I agree in this specific case: if the Leader attempts skew recovery, but the Helper has chosen not to implement it, the Helper would respond with a `stepMismatch` error.

So I think the state of things is: the Leader may optionally attempt to recover from skewed requests; the Helper may optionally implement skew recovery support. If both the Leader & the Helper implement their respective pieces, skew recovery is possible. Otherwise, it is not.

**Comment by cjpatton** [comment]
It sounds like you're saying the MUST is not required because the code path is fully specified in case the Helper doesn't implement skew recovery

If so, I don't think that's MT's point. Rather, the code path is only truly optional if the Helper supports it. In other words, the following statement is invalid:

> The Leader MAY do X. If the Leader does X, then the Helper SHOULD do Y.

Rather:

> The Leader MAY do X. If the Leader does X, then the Helper MUST do Y.

**Comment by martinthomson** [comment]
It might still be the case that the helper doesn't have to successfully handle the rollback and retry, but it can't fall over if the leader tries.

**Comment by branlwyd** [comment]
I surveyed the existing text around replay protection.

The Leader Initialization & Continuation sections don't say anything -- retrying by re-sending the same request again is left implicit. I think this is OK, but I could also see us adding some text if folks think it would be valuable.

The Helper aggregate initialization section says:

> Changing an aggregation job's parameters is illegal, so further HTTP PUT requests to /tasks/{task-id}/aggregation_jobs/{aggregation-job-id} for the same aggregation-job-id but with a different AggregationJobInitReq in the body MUST fail with an HTTP client error status code. For further requests with the same AggregationJobInitReq in the body, the Helper SHOULD respond as it did for the original AggregationJobInitReq, or otherwise fail with an HTTP client error status code.

> Additionally, it is not possible to rewind or reset the state of an aggregation job. Once an aggregation job has been continued at least once (see [Section 4.6.2](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#agg-continue-flow)), further requests to initialize that aggregation job MUST fail with an HTTP client error status code.


The Helper aggregate continuation section says:

> Next, the Helper checks if the continuation step indicated by the request is correct. (For the first AggregationJobContinueReq the value should be 1; for the second the value should be 2; and so on.) If the Leader is one step behind (e.g., the Leader has resent the previous HTTP request), then the Helper MAY attempt to recover by sending the same response as it did for the previous AggregationJobContinueReq, without performing any additional work on the aggregation job. In this case it SHOULD verify that the contents of the AggregationJobContinueReq are identical to the previous message (see [Section 4.6.2.4](https://ietf-wg-ppm.github.io/draft-ietf-ppm-dap/draft-ietf-ppm-dap.html#aggregation-step-skew-recovery)). Otherwise, if the step is incorrect, the Helper MUST abort with error stepMismatch.

And the Recovering from Aggregation Step Skew section does not add any relevant SHOULDs/MUSTs/etc.

I think we don't _need_ a change here; but if we do decide to add some text to the Leader sections suggesting retrying by re-sending the same message again, we could modify the last few sentences of the Helper aggregate continuation section to make it as clear as possible that a `stepMismatch` error is the required fallback for the case that the Helper does not wish to allow skew recovery. (e.g., "Otherwise, if the step is incorrect or if the Helper does not wish to attempt to recover, the Helper MUST abort with error stepmismatch.")

What do you think?

**Comment by cjpatton** [comment]
I like it!
