### ISSUE TITLE
Compare to alternatives

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-ppm/draft-ietf-ppm-dap#7]
We should probably describe applications wherein Prio is necessary (or at least desired) compared to other systems that might work, such as [ANONIZE](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.732.3675&rep=rep1&type=pdf). The original paper explains that the difference is in threat model: Prio assumes an adversary that can control the entire network, so outsourcing things to a proxy simply doesn't work. However, in practice, there may be circumstances wherein there *are* trusted proxies. In such cases, whether or not one actually wants to use them seems to depend on the application and data being collected. Specifically, if privacy depends on a collector not seeing individual client inputs, then Prio fits the bill, and if not, then perhaps simpler systems would work. It would probably be good to discuss this in more detail, if only to further motivate Prio.

**Comment by cjpatton** [comment]
Some alternatives worth considering:
* Use an [OHTTP](https://datatracker.ietf.org/doc/draft-thomson-http-oblivious/) proxy to strip personally identifiable metadata, like client IP, from reports. The downside is that the collector still sees the set of inputs (and not just the output, as in Prio or, to a lesser degree, HH).
* A pure differential privacy approach, like [RAPPOR](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/42852.pdf). The upside is that the communication model is much simpler, since RAPPOR doesn't require multiple aggregators. The downside is the privacy budget.

**Comment by cjpatton** [comment]
This still seems useful, but probably doesn't belong in the DAP spec. Closing for now... if someone wants to propose text, please feel free.
